/* Generated By:JJTree: Do not edit this line. ASTAssignmentExpression.java Version 4.3 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,
 * NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package org.dojo.jsl.parser.ast;

import java.util.HashMap;

import org.w3c.dom.Document;
import org.w3c.dom.Element;

import larac.LaraC;
import larac.objects.Variable;

public class ASTAssignmentExpression extends SimpleNode {
    public ASTAssignmentExpression(int id) {
        super(id);
    }

    public ASTAssignmentExpression(LARAEcmaScript p, int id) {
        super(p, id);
    }

    public SimpleNode solveInitializeAssignment(HashMap<String, Variable> vars) {
        final String operator = ((ASTOperator) getChildren()[1]).value.toString();
        final String varName = ((SimpleNode) getChildren()[0]).value.toString();
        if (!operator.equals("=")) {
            throw newException("Variable initizalization only supports the assignment operator \"=\"\n" + "\tUsed: \""
                    + operator + "\" for variable \"" + varName + "\"");
        }
        if (!(getChildren()[2] instanceof ASTAssignmentExpression)) {
            final SimpleNode expr = (SimpleNode) getChildren()[2];
            if (vars.containsKey(varName)) {
                throw newException("Variable '" + varName + "' already defined on this scope");
            }

            vars.put(varName, new Variable(varName));// , expr));
            return expr;
        }
        final ASTAssignmentExpression assignExpr = (ASTAssignmentExpression) getChildren()[2];
        final SimpleNode expr = assignExpr.solveInitializeAssignment(vars);
        if (vars.containsKey(varName)) {
            throw newException("Variable '" + varName + "' already defined on this scope");
        }
        vars.put(varName, new Variable(varName));
        expr.organize(this);
        return expr;
    }

    @Override
    public void declareGlobal(LaraC lara) {
        final SimpleNode assignee = (SimpleNode) getChildren()[0];
        final ASTOperator operator = (ASTOperator) getChildren()[1];
        final SimpleNode assignment = (SimpleNode) getChildren()[2];
        operator.organize(this);
        assignment.organize(this);
        assignee.organizeLHS(assignment.getExpressionType());
        getLara().aspectIR().addGlobalStatement(this, lara.getLaraPath());
    }

    @Override
    public Object organize(Object obj) {
        final SimpleNode assignee = (SimpleNode) getChildren()[0];
        final ASTOperator operator = (ASTOperator) getChildren()[1];
        final SimpleNode assignment = (SimpleNode) getChildren()[2];
        operator.organize(this);
        assignment.organize(this);
        assignee.organizeLHS(assignment.getExpressionType());
        return null;
    }

    @Override
    public void globalToXML(Document doc, Element parent) {
        final Element statEl = doc.createElement("declaration");
        statEl.setAttribute("name", "expr");
        statEl.setAttribute("coord", getCoords());
        parent.appendChild(statEl);
        final Element exprEl = doc.createElement("expression");
        statEl.appendChild(exprEl);
        toXML(doc, exprEl);
    }

    @Override
    public void toXML(Document doc, Element parent) {

        final SimpleNode assignee = (SimpleNode) getChildren()[0];
        final ASTOperator operator = (ASTOperator) getChildren()[1];
        final SimpleNode assignment = (SimpleNode) getChildren()[2];
        final Element assignEl = doc.createElement("op");
        parent.appendChild(assignEl);
        assignEl.setAttribute("name", operator.getTag());
        assignee.toXML(doc, assignEl);
        assignment.toXML(doc, assignEl);
    }
}
/*
 * JavaCC - OriginalChecksum=53aa17881f524d3978dc513d5dc2e458 (do not edit this
 * line)
 */
