/* Generated By:JJTree: Do not edit this line. ASTCaseGroup.java Version 4.3 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,
 * NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package org.dojo.jsl.parser.ast;

import org.w3c.dom.Document;
import org.w3c.dom.Element;

public class ASTCaseGroup extends SimpleNode {
	public ASTCaseGroup(int id) {
		super(id);
	}

	public ASTCaseGroup(LARAEcmaScript p, int id) {
		super(p, id);
	}

	@Override
	public Object organize(Object obj) {
		for (int i = 0; i < children.length; i++) {
			((SimpleNode) children[i]).organize(obj);
		}
		return null;
	}

	@Override
	public void toXML(Document doc, Element parent) {
		if (((SimpleNode) children[0]).children != null) {
			final Element caseGuard = doc.createElement("expression");
			parent.appendChild(caseGuard);
			caseGuard.setAttribute("desc", "case");
			((SimpleNode) children[0]).toXML(doc, caseGuard);
		}

		final Element caseBody = doc.createElement("code");
		parent.appendChild(caseBody);
		if (((SimpleNode) children[0]).children == null) {
			caseBody.setAttribute("desc", "default");
		} else {
			caseBody.setAttribute("desc", "case_body");
		}
		if (children.length > 1) {
			((SimpleNode) children[1]).toXML(doc, caseBody);
		}

	}
}
/*
 * JavaCC - OriginalChecksum=38619f15d78f6fa5a9e5d10df4d3adb6 (do not edit this
 * line)
 */
