/* Generated By:JJTree: Do not edit this line. ASTCaseGroups.java Version 4.3 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,
 * NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package org.dojo.jsl.parser.ast;

import org.w3c.dom.Document;
import org.w3c.dom.Element;

public class ASTCaseGroups extends SimpleNode {
	public ASTCaseGroups(int id) {
		super(id);
	}

	public ASTCaseGroups(LARAEcmaScript p, int id) {
		super(p, id);
	}

	@Override
	public Object organize(Object obj) {
		for (int i = 0; i < children.length; i++) {
			((SimpleNode) children[i]).organize(obj);
		}
		return null;
	}

	@Override
	public void toXML(Document doc, Element parent) {
		for (final Node child : children) {
			((SimpleNode) child).toXML(doc, parent);
		}
	}

}
/*
 * JavaCC - OriginalChecksum=226233d49a1eac506d313d7e34ec97d9 (do not edit this
 * line)
 */
