/* Generated By:JJTree: Do not edit this line. ASTCaseGuard.java Version 4.3 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,
 * NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package org.dojo.jsl.parser.ast;

import org.w3c.dom.Document;
import org.w3c.dom.Element;

public class ASTCaseGuard extends SimpleNode {
	public ASTCaseGuard(int id) {
		super(id);
	}

	public ASTCaseGuard(LARAEcmaScript p, int id) {
		super(p, id);
	}

	@Override
	public Object organize(Object obj) {
		if (children != null) {
			for (int i = 0; i < children.length; i++) {
				((SimpleNode) children[i]).organize(obj);
			}
		}
		return null;
	}

	@Override
	public void toXML(Document doc, Element parent) {
		((SimpleNode) children[0]).toXML(doc, parent);
	}

}
/*
 * JavaCC - OriginalChecksum=799bec44f37b0399bfed673d6b6ac113 (do not edit this
 * line)
 */
