/* Generated By:JJTree: Do not edit this line. ASTDoStatement.java Version 4.3 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,
 * NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package org.dojo.jsl.parser.ast;

import org.w3c.dom.Document;
import org.w3c.dom.Element;

import larac.objects.Enums;

public class ASTDoStatement extends SimpleNode {
	public ASTDoStatement(int id) {
		super(id);
	}

	public ASTDoStatement(LARAEcmaScript p, int id) {
		super(p, id);
	}

	@Override
	public Object organize(Object obj) {
		for (int i = 0; i < children.length; i++) {
			((SimpleNode) children[i]).organize(obj);
		}
		return null;
	}

	@Override
	public void toXML(Document doc, Element parent) {
		final Element stmtEl = doc.createElement("statement");
		stmtEl.setAttribute("name", "loop");
		stmtEl.setAttribute("desc", Enums.LoopTypes.DO.toString());
		stmtEl.setAttribute("coord", getCoords());
		if (!label.isEmpty()) {
			stmtEl.setAttribute("label", label);
		}
		parent.appendChild(stmtEl);

		final Element codeEl = doc.createElement("code");
		codeEl.setAttribute("desc", "body");
		stmtEl.appendChild(codeEl);
		((SimpleNode) children[0]).toXML(doc, codeEl);

		final Element conditionEl = doc.createElement("expression");
		conditionEl.setAttribute("desc", "condition");
		stmtEl.appendChild(conditionEl);
		((SimpleNode) children[1]).toXML(doc, conditionEl);
	}

}
/*
 * JavaCC - OriginalChecksum=897d48445d115989cc12cd03d158c619 (do not edit this
 * line)
 */
