/* Generated By:JJTree: Do not edit this line. ASTExpressionStatement.java Version 4.3 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,
 * NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package org.dojo.jsl.parser.ast;

import org.w3c.dom.Document;
import org.w3c.dom.Element;

public class ASTExpressionStatement extends SimpleNode {
	public ASTExpressionStatement(int id) {
		super(id);
	}

	public ASTExpressionStatement(LARAEcmaScript p, int id) {
		super(p, id);
	}

	@Override
	public Object organize(Object obj) {
		for (final Node child : getChildren()) {
			((SimpleNode) child).organize(obj);
		}
		return null;
	}

	@Override
	public void toXML(Document doc, Element parent) {
		for (final Node child : getChildren()) {

			if (!insertTag) {
				((SimpleNode) child).toXML(doc, parent);
				continue;
			}
			final Element statEl = doc.createElement("statement");
			statEl.setAttribute("coord", getCoords());
			if (!label.isEmpty()) {
				statEl.setAttribute("label", label);
			}
			parent.appendChild(statEl);
			statEl.setAttribute("name", "expr");

			final Element exprEl = doc.createElement("expression");
			statEl.appendChild(exprEl);
			((SimpleNode) child).toXML(doc, exprEl);
		}
	}
}
/*
 * JavaCC - OriginalChecksum=b35cf230ca3a5f40e973934bf7137de1 (do not edit this
 * line)
 */
