/* Generated By:JJTree: Do not edit this line. ASTEmptyStatement.java Version 4.3 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,
 * NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package org.dojo.jsl.parser.ast;

import org.w3c.dom.Document;
import org.w3c.dom.Element;

public class ASTEmptyStatement extends SimpleNode {
	public ASTEmptyStatement(int id) {
		super(id);
	}

	public ASTEmptyStatement(LARAEcmaScript p, int id) {
		super(p, id);
	}

	@Override
	public Object organize(Object obj) {
		return null;
	}

	@Override
	public void toXML(Document doc, Element parent) {
	}
}
/*
 * JavaCC - OriginalChecksum=7e1f751f351af514d125ee662e6798cf (do not edit this
 * line)
 */
