/* Generated By:JJTree: Do not edit this line. ASTElision.java Version 4.3 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,
 * NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package org.dojo.jsl.parser.ast;

public class ASTEmptyPositions extends SimpleNode {
	private int count = 0;

	public ASTEmptyPositions(int id) {
		super(id);
	}

	public ASTEmptyPositions(LARAEcmaScript p, int id) {
		super(p, id);
	}

	public void inc() {
		count++;
	}

	public void setCount(int count) {
		this.count = count;
	}

	public int getCount() {
		return count;
	}

	@Override
	public String toString() {
		return LARAEcmaScriptTreeConstants.jjtNodeName[id] + " [" + count + "]";
	}

	@Override
	public Object organize(Object obj) {
		return null;
	}

	/*
	 * @Override public void toXML(Document doc, Element parent) { for(int i=0;
	 * i< count; i++){ Element undefinedEl = doc.createElement("literal");
	 * parent.appendChild(undefinedEl); undefinedEl.setAttribute("type",
	 * "undefined"); } }
	 */
}
/*
 * JavaCC - OriginalChecksum=85fc01c554e46918aacba6da481a56c8 (do not edit this
 * line)
 */
