/* Generated By:JJTree: Do not edit this line. ASTEmptyExpression.java Version 4.3 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,
 * NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package org.dojo.jsl.parser.ast;

import org.w3c.dom.Document;
import org.w3c.dom.Element;

public class ASTEmptyExpression extends SimpleNode {
	public ASTEmptyExpression(int id) {
		super(id);
	}

	public ASTEmptyExpression(LARAEcmaScript p, int id) {
		super(p, id);
	}

	@Override
	public Object organize(Object obj) {
		return null;
	}

	@Override
	public void toXML(Document doc, Element parent) {
	}
}
/*
 * JavaCC - OriginalChecksum=c2bec030feafd4d42271955a4767fe69 (do not edit this
 * line)
 */
