/* Generated By:JJTree: Do not edit this line. ASTForStatement.java Version 4.3 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,
 * NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package org.dojo.jsl.parser.ast;

import org.w3c.dom.Document;
import org.w3c.dom.Element;

import larac.objects.Enums;

public class ASTForStatement extends SimpleNode {
	public ASTForStatement(int id) {
		super(id);
	}

	public ASTForStatement(LARAEcmaScript p, int id) {
		super(p, id);
	}

	@Override
	public Object organize(Object obj) {
		for (int i = 0; i < children.length; i++) {
			((SimpleNode) children[i]).organize(obj);
		}
		return null;
	}

	@Override
	public void toXML(Document doc, Element parent) {

		final Element statEl = doc.createElement("statement");
		parent.appendChild(statEl);

		statEl.setAttribute("coord", getCoords());
		statEl.setAttribute("name", "loop");
		statEl.setAttribute("desc", Enums.LoopTypes.FOR.toString());
		if (!label.isEmpty()) {
			statEl.setAttribute("label", label);
		}
		final Element initEl = doc.createElement("code");
		statEl.appendChild(initEl);
		initEl.setAttribute("desc", "init");
		final Element statExprEl = doc.createElement("statement");
		statExprEl.setAttribute("name", "expr");
		statExprEl.setAttribute("coord", getCoords());
		initEl.appendChild(statExprEl);
		final Element exprEl = doc.createElement("expression");
		statExprEl.appendChild(exprEl);
		((SimpleNode) children[0]).toXML(doc, exprEl);

		final Element conditionEl = doc.createElement("expression");
		statEl.appendChild(conditionEl);
		conditionEl.setAttribute("desc", "condition");
		((SimpleNode) children[1]).toXML(doc, conditionEl);
		final Element codeEl = doc.createElement("code");
		statEl.appendChild(codeEl);
		codeEl.setAttribute("desc", "body");
		((SimpleNode) children[3]).toXML(doc, codeEl);

		final Element exprItEl = doc.createElement("expression");
		statEl.appendChild(exprItEl);
		((SimpleNode) children[2]).toXML(doc, exprItEl);
	}
}
/*
 * JavaCC - OriginalChecksum=512f5c288d5c705f5c8200c17c94ad98 (do not edit this
 * line)
 */
