/* Generated By:JJTree: Do not edit this line. ASTFinalize.java Version 4.3 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,
 * NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package org.dojo.jsl.parser.ast;

import org.w3c.dom.Document;
import org.w3c.dom.Element;

public class ASTFinalize extends SimpleNode {
	public ASTFinalize(int id) {
		super(id);
	}

	public ASTFinalize(LARAEcmaScript p, int id) {
		super(p, id);
	}

	@Override
	public Object organize(Object obj) {
		if (((SimpleNode) getChildren()[0]).getChildren() == null) {
			return null;
		}
		((SimpleNode) getChildren()[0]).organize(obj);
		((ASTAspectDef) parent).setFinalize(this);
		return null;
	}

	@Override
	public void toXML(Document doc, Element parent) {
		final Element finEl = doc.createElement("finalize");
		parent.appendChild(finEl);
		((SimpleNode) getChildren()[0]).toXML(doc, finEl);
	}
}
/*
 * JavaCC - OriginalChecksum=5f4f89815e48640eb1f1c355e69eb115 (do not edit this
 * line)
 */
