/* Generated By:JJTree: Do not edit this line. ASTForInStatement.java Version 4.3 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,
 * NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package org.dojo.jsl.parser.ast;

import org.w3c.dom.Document;
import org.w3c.dom.Element;

import larac.objects.Enums.LoopTypes;

public class ASTForInStatement extends SimpleNode {
	private boolean each = false;

	public ASTForInStatement(int id) {
		super(id);
	}

	public ASTForInStatement(LARAEcmaScript p, int id) {
		super(p, id);
	}

	@Override
	public Object organize(Object obj) {
		for (int i = 0; i < children.length; i++) {
			((SimpleNode) children[i]).organize(obj);
		}
		return null;
	}

	@Override
	public void toXML(Document doc, Element parent) {
		final Element stmtEl = doc.createElement("statement");
		stmtEl.setAttribute("name", "loop");
		final LoopTypes loopType = isEach() ? LoopTypes.FOREACH : LoopTypes.FORIN;
		stmtEl.setAttribute("desc", loopType.toString());
		stmtEl.setAttribute("coord", getCoords());
		parent.appendChild(stmtEl);
		if (!label.isEmpty()) {
			stmtEl.setAttribute("label", label);
		}
		final Element initEl = doc.createElement("code");
		initEl.setAttribute("desc", "init");
		stmtEl.appendChild(initEl);
		final Element statExprEl = doc.createElement("statement");
		statExprEl.setAttribute("name", "expr");
		statExprEl.setAttribute("coord", getCoords());
		initEl.appendChild(statExprEl);
		final Element exprEl = doc.createElement("expression");
		statExprEl.appendChild(exprEl);
		((SimpleNode) children[0]).toXML(doc, exprEl);

		final Element containerEl = doc.createElement("expression");
		containerEl.setAttribute("desc", "container");
		stmtEl.appendChild(containerEl);
		((SimpleNode) children[1]).toXML(doc, containerEl);

		final Element codeEl = doc.createElement("code");
		codeEl.setAttribute("desc", "body");
		stmtEl.appendChild(codeEl);
		((SimpleNode) children[2]).toXML(doc, codeEl);
	}

	public boolean isEach() {
		return each;
	}

	public void setEach(boolean each) {
		this.each = each;
	}
}
/*
 * JavaCC - OriginalChecksum=dc8c61704cfc22f28f18f34b4cbc3b3a (do not edit this
 * line)
 */
