/* Generated By:JJTree: Do not edit this line. ASTFilePath.java Version 4.3 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,
 * NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package org.dojo.jsl.parser.ast;

public @SuppressWarnings("all") class ASTFilePath extends SimpleNode {
	public ASTFilePath(int id) {
		super(id);
	}

	public ASTFilePath(LARAEcmaScript p, int id) {
		super(p, id);
	}

}
/*
 * JavaCC - OriginalChecksum=df6115dbbe0fb927a6088321e1af3714 (do not edit this
 * line)
 */
