/* Generated By:JJTree: Do not edit this line. ASTInitialize.java Version 4.3 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,
 * NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package org.dojo.jsl.parser.ast;

import org.w3c.dom.Document;
import org.w3c.dom.Element;

public class ASTInitialize extends SimpleNode {
	public ASTInitialize(int id) {
		super(id);
	}

	public ASTInitialize(LARAEcmaScript p, int id) {
		super(p, id);
	}

	@Override
	public Object organize(Object obj) {
		if (((SimpleNode) getChildren()[0]).getChildren() == null) {
			return null;
		}
		((SimpleNode) getChildren()[0]).organize(obj);
		((ASTAspectDef) parent).setInitialize(this);
		return null;
	}

	@Override
	public void toXML(Document doc, Element parent) {
		final Element initEl = doc.createElement("initialize");
		parent.appendChild(initEl);
		((SimpleNode) getChildren()[0]).toXML(doc, initEl);
	}
}
/*
 * JavaCC - OriginalChecksum=e670fa2115c280692f65386d9b0bdfb4 (do not edit this
 * line)
 */
