/* Generated By:JJTree: Do not edit this line. ASTInclude.java Version 4.3 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,
 * NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package org.dojo.jsl.parser.ast;

public class ASTInclude extends SimpleNode {
	public ASTInclude(int id) {
		super(id);
	}

	public ASTInclude(LARAEcmaScript p, int id) {
		super(p, id);
	}

}
/*
 * JavaCC - OriginalChecksum=13a79f3491a3f2efc06dbcd9003d4157 (do not edit this
 * line)
 */
