/* Generated By:JJTree: Do not edit this line. ASTLiteralField.java Version 4.3 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,
 * NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package org.dojo.jsl.parser.ast;

public @SuppressWarnings("all") class ASTLiteralField extends SimpleNode {
	public ASTLiteralField(int id) {
		super(id);
	}

	public ASTLiteralField(LARAEcmaScript p, int id) {
		super(p, id);
	}

}
/*
 * JavaCC - OriginalChecksum=0f6af9d9a7db9dfb202ef74b938fbc2e (do not edit this
 * line)
 */
