/* Generated By:JJTree: Do not edit this line. ASTORJPExpr.java Version 4.3 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,
 * NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package org.dojo.jsl.parser.ast;

import org.w3c.dom.Document;
import org.w3c.dom.Element;

public class ASTORJPExpr extends SimpleNode {
	public ASTORJPExpr(int id) {
		super(id);
	}

	public ASTORJPExpr(LARAEcmaScript p, int id) {
		super(p, id);
	}

	@Override
	public Object organize(Object obj) {

		for (final Node child : getChildren()) {
			((SimpleNode) child).organize(obj);
		}
		return null;
	}

	@Override
	public Object organizeFirst(Object obj, int dummy) {

		for (int i = 0; i < getChildren().length; i++) {
			((SimpleNode) getChildren()[i]).organizeFirst(obj, i);
		}
		return null;
	}

	@Override
	public void toXML(Document doc, Element parent) {
		for (final Node child : getChildren()) {
			((SimpleNode) child).toXML(doc, parent);
		}
	}

	@Override
	public boolean hasFilter() {
		for (final Node child : getChildren()) {
			if (((SimpleNode) child).hasFilter()) {
				return true;
			}
		}
		return false;
	}
}
/*
 * JavaCC - OriginalChecksum=809ee13c569e1e4397220af63595e13e (do not edit this
 * line)
 */
