/* Generated By:JJTree: Do not edit this line. ASTPostAssignmentList.java Version 4.3 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,
 * NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package org.dojo.jsl.parser.ast;

import org.w3c.dom.Document;
import org.w3c.dom.Element;

public class ASTPostAssignmentList extends SimpleNode {
	public ASTPostAssignmentList(int id) {
		super(id);
	}

	public ASTPostAssignmentList(LARAEcmaScript p, int id) {
		super(p, id);
	}

	@Override
	public Object organize(Object obj) {
		for (int i = 0; i < children.length; i++) {
			((SimpleNode) children[i]).organize(obj);
		}
		return null;
	}

	@Override
	public void toXML(Document doc, Element parent) {
		for (int i = 0; i < children.length; i++) {
			((SimpleNode) children[i]).toXML(doc, parent);
		}
	}
}
/*
 * JavaCC - OriginalChecksum=3436d21d14d367e791f53c8a9e7d0b32 (do not edit this
 * line)
 */
