/* Generated By:JJTree: Do not edit this line. ASTPropertyValueReference.java Version 4.3 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,
 * NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package org.dojo.jsl.parser.ast;

import org.w3c.dom.Document;
import org.w3c.dom.Element;

public class ASTPropertyValueReference extends SimpleNode {
	public ASTPropertyValueReference(int id) {
		super(id);
	}

	public ASTPropertyValueReference(LARAEcmaScript p, int id) {
		super(p, id);
	}

	@Override
	public Object organize(Object obj) {
		return ((SimpleNode) children[0]).organize(obj);
	}

	@Override
	public void toXML(Document doc, Element parent) {
		((SimpleNode) children[0]).toXML(doc, parent);
	}
}
/*
 * JavaCC - OriginalChecksum=a9e3d25c9236ea41f6a673f87a9ca4a5 (do not edit this
 * line)
 */
