/* Generated By:JJTree: Do not edit this line. ASTStatementList.java Version 4.3 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,
 * NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package org.dojo.jsl.parser.ast;

import org.w3c.dom.Document;
import org.w3c.dom.Element;

public class ASTStatementList extends SimpleNode {
	public ASTStatementList(int id) {
		super(id);
	}

	public ASTStatementList(LARAEcmaScript p, int id) {
		super(p, id);
	}

	@Override
	public Object organize(Object obj) {
		for (final Node child : getChildren()) {
			((SimpleNode) child).organize(obj);
		}
		return null;
	}

	@Override
	public void toXML(Document doc, Element parent) {
		for (final Node child : getChildren()) {
			((SimpleNode) child).toXML(doc, parent);
		}
	}
}
/*
 * JavaCC - OriginalChecksum=abb3ed87f64e250c8d785390504b91ff (do not edit this
 * line)
 */
