/* Generated By:JJTree: Do not edit this line. ASTSwitchStatement.java Version 4.3 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,
 * NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package org.dojo.jsl.parser.ast;

import org.w3c.dom.Document;
import org.w3c.dom.Element;

public class ASTSwitchStatement extends SimpleNode {
	public ASTSwitchStatement(int id) {
		super(id);
	}

	public ASTSwitchStatement(LARAEcmaScript p, int id) {
		super(p, id);
	}

	@Override
	public Object organize(Object obj) {
		for (int i = 0; i < children.length; i++) {
			((SimpleNode) children[i]).organize(obj);
		}
		return null;
	}

	@Override
	public void toXML(Document doc, Element parent) {
		final Element statEl = doc.createElement("statement");
		parent.appendChild(statEl);
		statEl.setAttribute("name", "switch");
		statEl.setAttribute("coord", getCoords());
		if (!label.isEmpty()) {
			statEl.setAttribute("label", label);
		}
		final Element swEl = doc.createElement("expression");
		statEl.appendChild(swEl);
		swEl.setAttribute("desc", "switcher");
		((SimpleNode) children[0]).toXML(doc, swEl);

		((SimpleNode) children[1]).toXML(doc, statEl);
	}

}
/*
 * JavaCC - OriginalChecksum=c4be2b1ffd729f6b6c4034f162aad0e4 (do not edit this
 * line)
 */
