/* Generated By:JJTree: Do not edit this line. ASTThirdSetOp.java Version 4.3 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,
 * NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package org.dojo.jsl.parser.ast;

public class ASTThirdSetOp extends SimpleNode {
	public ASTThirdSetOp(int id) {
		super(id);
	}

	public ASTThirdSetOp(LARAEcmaScript p, int id) {
		super(p, id);
	}

}
/*
 * JavaCC - OriginalChecksum=69404b05376c45d8012af93aee712405 (do not edit this
 * line)
 */
