/* Generated By:JJTree: Do not edit this line. ASTThrowStatement.java Version 4.3 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,
 * NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package org.dojo.jsl.parser.ast;

import org.w3c.dom.Document;
import org.w3c.dom.Element;

public class ASTThrowStatement extends SimpleNode {
	public ASTThrowStatement(int id) {
		super(id);
	}

	public ASTThrowStatement(LARAEcmaScript p, int id) {
		super(p, id);
	}

	@Override
	public Object organize(Object obj) {
		return ((SimpleNode) children[0]).organize(obj);
	}

	@Override
	public void toXML(Document doc, Element parent) {
		final Element statEl = doc.createElement("statement");
		statEl.setAttribute("name", "throw");
		statEl.setAttribute("coord", getCoords());
		parent.appendChild(statEl);
		final Element exprEl = doc.createElement("expression");
		statEl.appendChild(exprEl);
		((SimpleNode) children[0]).toXML(doc, exprEl);
	}
}
/*
 * JavaCC - OriginalChecksum=d4955a4ea899d87a9870aeeab52a0554 (do not edit this
 * line)
 */
