/* Generated By:JJTree: Do not edit this line. ASTYieldStar.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.dojo.jsl.parser.ast;

public
class ASTYieldStar extends SimpleNode {
  public ASTYieldStar(int id) {
    super(id);
  }

  public ASTYieldStar(LARAEcmaScript p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f6f1584e0e6a0e6647b3291913e4cfaf (do not edit this line) */
