/* Generated By:JJTree: Do not edit this line. ASTYieldStar.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.dojo.jsl.parser.ast;

public
class ASTYieldStar extends SimpleNode {
  public ASTYieldStar(int id) {
    super(id);
  }

  public ASTYieldStar(LARAEcmaScript p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=323cf70695742d00aedb5b915073d67e (do not edit this line) */
