package org.lara.weavergen2.generator;

import org.lara.langspec2.model.*;
import org.lara.langspec2.types.JpDataType;
import org.lara.langspec2.types.JpDataType.*;
import org.lara.weavergen2.java.JavaSourceBuilder;
import org.lara.weavergen2.java.TypeMapper;

import java.nio.file.*;
import java.util.*;
import java.util.function.Function;
import java.util.regex.*;

/**
 * Generates an abstract join point class from a {@link JpClass}.
 * <p>
 * This generates abstract classes where inherited methods are resolved through
 * the Java class hierarchy.
 */
public final class AbstractJpGenerator {

    private final JpClass jpClass;
    private final WeaverModel model;
    private final GeneratorConfig config;

    public AbstractJpGenerator(JpClass jpClass, WeaverModel model, GeneratorConfig config) {
        this.jpClass = jpClass;
        this.model = model;
        this.config = config;
    }

    public String generate() {
        var sb = new JavaSourceBuilder();
        var standaloneMode = !config.hasBaseSpec();

        // Package
        sb.line("package " + config.joinPointPackage() + ";");
        sb.line();

        // Imports
        generateImports(sb);
        if (standaloneMode) {
            sb.line("import pt.up.fe.specs.jsengine.node.UndefinedValue;");
        }
        sb.line();

        // Class declaration
        var className = TypeMapper.abstractClassName(jpClass.getName());
        String superClass = null;
        if (!standaloneMode) {
            if (jpClass == model.getGlobal()) {
                superClass = getConcreteSuperclass(jpClass) + "<Self, " + className + "<?>>";
            } else {
                superClass = getConcreteSuperclass(jpClass) + "<Self>";
            }
        }

        sb.line("/**");
        sb.line(" * Auto-generated abstract class for the {@code " + jpClass.getName() + "} join point.");
        sb.line(" * <p>");
        sb.line(" * This class is generated by WeaverGen2 and should not be edited manually.");
        sb.line(" */");
        if (superClass == null) {
            sb.openBlock("public abstract class " + className + "<Self extends " + className + "<Self, Jp>, Jp extends "
                    + className + "<?, Jp>>");
        } else {
            sb.openBlock("public abstract class " + className + "<Self extends " + className + "<Self>> extends "
                    + superClass);
        }
        sb.line();

        if (!standaloneMode) {
            // Constructor
            var nodeType = simpleClassName(config.nodeType());
            if (hasConcreteSuperclassNodeTypeCast(jpClass)) {
                nodeType = getConcreteSuperclassNodeType(jpClass);
            }

            var constructorWeaverType = getConstructorWeaverType(jpClass);
            if (jpClass == model.getGlobal()) {

                sb.line("// FIXME: This should be a private field");
                sb.line("protected " + nodeType + " node;");
                sb.line();
                sb.openBlock("public " + className + "(" + nodeType + " node, "
                        + config.weaverClassName() + " weaver)");
                sb.line("super(weaver);");
                sb.line("this.node = node;");
                sb.closeBlock();
                sb.line();

                sb.openBlock("public " + nodeType + " getNode()");
                sb.line("return node;");
                sb.closeBlock();
                sb.line();
            }
            else {
                sb.openBlock("public " + className + "(" + nodeType + " node, " + constructorWeaverType + " weaver)");
                sb.line("super(node, weaver);");
                sb.closeBlock();
                sb.line();
            }
        }

        // Own attributes
        for (var attr : jpClass.getOwnAttributes()) {
            generateOwnAttribute(sb, attr);
        }

        // Own actions
        for (var action : jpClass.getOwnActions()) {
            generateOwnAction(sb, action);
        }

        // get_class()
        if (config.hasBaseSpec()) {
            sb.line("@Override");
        }
        sb.openBlock("public String get_class()");
        sb.line("return \"" + jpClass.getName() + "\";");
        sb.closeBlock();
        sb.line();

        // instanceOf()
        generateInstanceOf(sb);

        if (standaloneMode) {
            sb.line();
            sb.openBlock("public static Object getUndefinedValue()");
            sb.line("return UndefinedValue.getUndefined();");
            sb.closeBlock();
        }

        sb.closeBlock(); // class

        return sb.toString();
    }

    private void generateImports(JavaSourceBuilder sb) {
        var standaloneMode = !config.hasBaseSpec();

        if (!standaloneMode) {
            sb.line("import " + config.baseJoinPointPackage() + ".*;");
            sb.line("import " + getConstructorWeaverImport(jpClass) + ";");
            var parentConcreteImport = getConcreteSuperclassImport(jpClass);
            if (parentConcreteImport.isPresent()) {
                sb.line("import " + parentConcreteImport.get() + ";");
            }
            sb.line("import " + config.nodeType() + ";");
            var concreteSuperclassNodeTypeImport = getConcreteSuperclassNodeTypeImport(jpClass);
            if (concreteSuperclassNodeTypeImport.isPresent()
                    && !concreteSuperclassNodeTypeImport.get().equals(config.nodeType())) {
                sb.line("import " + concreteSuperclassNodeTypeImport.get() + ";");
            }
        }
        if (!model.getTypeDefs().isEmpty()) {
            sb.line("import " + config.entitiesPackage() + ".*;");
        }
        if (!model.getEnumDefs().isEmpty()) {
            sb.line("import " + config.enumsPackage() + ".*;");
        }
        sb.line("import org.lara.interpreter.exception.ActionException;");
        sb.line("import org.lara.interpreter.exception.AttributeException;");
        sb.line();
        sb.line("import java.util.*;");
    }

    private String simpleClassName(String fullyQualifiedName) {
        var lastDot = fullyQualifiedName.lastIndexOf('.');
        return lastDot < 0 ? fullyQualifiedName : fullyQualifiedName.substring(lastDot + 1);
    }

    private String getConcreteSuperclass(JpClass jpClass) {
        if (jpClass == model.getGlobal()) {
            return config.baseJoinPointClass();
        }

        var parent = jpClass.getParent().orElseThrow();
        return concreteClassName(parent);
    }

    private Optional<String> getConcreteSuperclassImport(JpClass jpClass) {
        if (jpClass == model.getGlobal()) {
            return Optional.empty();
        }

        var parent = jpClass.getParent().orElseThrow();
        var concretePackage = concretePackage(parent);
        var concreteClass = concreteClassName(parent);

        return Optional.of(concretePackage + "." + concreteClass);
    }

    private String getConcreteSuperclassNodeType(JpClass jpClass) {
        var nodeTypeImport = getConcreteSuperclassNodeTypeImport(jpClass)
                .orElseThrow(() -> new IllegalStateException(
                        "Could not resolve constructor node type for join point '" + jpClass.getName() + "'"));

        return simpleClassName(nodeTypeImport);
    }

    private Optional<String> getConcreteSuperclassNodeTypeImport(JpClass jpClass) {
        if (jpClass == model.getGlobal() || jpClass.getParent().map(parent -> parent.equals(model.getGlobal())).orElse(false)) {
            return Optional.of(config.nodeType());
        }

        var concreteSuperclassImport = getConcreteSuperclassImport(jpClass)
                .orElseThrow(() -> new IllegalStateException(
                        "Could not resolve concrete superclass for join point '" + jpClass.getName() + "'"));

        try {
            var sourceFile = resolveSourceFile(concreteSuperclassImport)
                    .orElseThrow(() -> new IllegalStateException("Could not locate source file for concrete superclass '"
                            + concreteSuperclassImport + "' while generating join point '" + jpClass.getName() + "'"));

            var source = Files.readString(sourceFile);
            var concreteSuperclassName = simpleClassName(concreteSuperclassImport);
            var constructorMatcher = Pattern.compile("public\\s+" + Pattern.quote(concreteSuperclassName)
                    + "\\s*\\(([^)]*)\\)", Pattern.DOTALL).matcher(source);

            if (!constructorMatcher.find()) {
                throw new IllegalStateException("Could not find constructor signature for '" + concreteSuperclassImport
                        + "' in source file '" + sourceFile + "'");
            }

            var parameters = constructorMatcher.group(1).trim();
            var firstParameter = parameters.split(",", 2)[0].trim();
            var firstSpace = firstParameter.lastIndexOf(' ');

            if (firstSpace < 0) {
                throw new IllegalStateException("Could not parse first constructor parameter of '"
                        + concreteSuperclassImport + "' from source file '" + sourceFile + "'");
            }

            var nodeTypeSimpleName = firstParameter.substring(0, firstSpace).trim();
            return Optional.of(resolveNodeTypeImport(source, sourceFile, concreteSuperclassImport, nodeTypeSimpleName));
        } catch (java.io.IOException e) {
            throw new IllegalStateException("Could not read source file for concrete superclass '"
                    + concreteSuperclassImport + "' while generating join point '" + jpClass.getName() + "'", e);
        }
    }

    private Optional<Path> resolveSourceFile(String fullyQualifiedClassName) {
        var relativePath = fullyQualifiedClassName.replace('.', '/') + ".java";
        var sourceRoots = List.of("src", "src-java", "src/main/java");

        for (var sourceRoot : sourceRoots) {
            var sourceFile = Path.of(System.getProperty("user.dir"), sourceRoot).resolve(relativePath);
            if (Files.exists(sourceFile)) {
                return Optional.of(sourceFile);
            }
        }

        return Optional.empty();
    }

    private String resolveNodeTypeImport(String source,
            Path sourceFile,
            String concreteSuperclassImport,
            String nodeTypeSimpleName) {

        if (nodeTypeSimpleName.contains(".")) {
            return nodeTypeSimpleName;
        }

        if (TypeMapper.isPrimitive(nodeTypeSimpleName)) {
            return nodeTypeSimpleName;
        }

        try {
            Class.forName("java.lang." + nodeTypeSimpleName);
            return "java.lang." + nodeTypeSimpleName;
        } catch (ClassNotFoundException e) {
            // Not a java.lang type, continue resolving from imports below.
        }

        var importMatcher = Pattern.compile("^import\\s+([^;]+\\." + Pattern.quote(nodeTypeSimpleName) + ");$",
                Pattern.MULTILINE).matcher(source);

        if (importMatcher.find()) {
            return importMatcher.group(1);
        }

        throw new IllegalStateException("Could not resolve import for constructor node type '" + nodeTypeSimpleName
                + "' in concrete superclass '" + concreteSuperclassImport + "' from source file '" + sourceFile + "'");
    }

    private boolean hasConcreteSuperclassNodeTypeCast(JpClass jpClass) {
        return jpClass.getParent().map(parent -> !parent.equals(model.getGlobal())).orElse(false);
    }

    private String concreteClassName(JpClass jpClass) {
        if (jpClass == model.getGlobal()) {
            return config.userAbstractClassName();
        }

        return "Cxx" + TypeMapper.capitalize(jpClass.getName());
    }

    private String concretePackage(JpClass jpClass) {
        if (jpClass == model.getGlobal()) {
            return config.abstractsPackage();
        }

        var concreteBasePackage = config.basePackage() + ".joinpoints";

        if (isCilkBranch(jpClass)) {
            return concreteBasePackage + ".cilk";
        }

        if (isTypeBranch(jpClass)) {
            return concreteBasePackage + ".types";
        }

        return concreteBasePackage;
    }

    private boolean isTypeBranch(JpClass jpClass) {
        var typeRoot = findJpClass("type");
        return typeRoot != null && jpClass.isOrExtends(typeRoot);
    }

    private boolean isCilkBranch(JpClass jpClass) {
        return jpClass.getName().toLowerCase(Locale.ROOT).startsWith("cilk");
    }

    private JpClass findJpClass(String name) {
        return model.getAllJpClasses().stream()
                .filter(jp -> jp.getName().equals(name))
                .findFirst()
                .orElse(null);
    }

    private void generateOwnAttribute(JavaSourceBuilder sb, Attribute attr) {
        var javaRetType = mapReturnType(attr.type());
        var methodName = "get" + TypeMapper.capitalize(attr.name());
        var implMethodName = methodName + "Impl";

        if (attr.parameters().isEmpty()) {
            sb.line("public abstract " + javaRetType + " " + implMethodName + "();");
        } else {
            var params = formatParams(attr.parameters());
            sb.line("public abstract " + javaRetType + " " + implMethodName + "(" + params + ");");
        }
        sb.line();

        if (shouldGenerateWrapper(attr.name(), attr.parameters())) {
            generateFinalWrapper(sb, attr.name(), methodName, attr.type(), attr.parameters(), true);
        }
    }

    private void generateOwnAction(JavaSourceBuilder sb, Action action) {
        var javaRetType = mapReturnType(action.returnType());
        var methodName = action.name();
        var implMethodName = methodName + "Impl";

        var paramStr = formatParams(action.parameters());

        // Impl method (default: throws)
        sb.openBlock("public " + javaRetType + " " + implMethodName + "(" + paramStr + ")");
        sb.line("throw new UnsupportedOperationException(get_class() + \": Action " + action.name()
                + " not implemented\");");
        sb.closeBlock();
        sb.line();

        if (shouldGenerateWrapper(action.name(), action.parameters())) {
            generateActionFinalWrapper(sb, action);
        }
    }

    private void generateFinalWrapper(JavaSourceBuilder sb, String attrName, String methodName,
            JpDataType type, List<Parameter> params, boolean isAttribute) {
        var isSelfOrJp = type instanceof SelfType || type instanceof JpRefType;
        var wrapperReturnType = "Object";
        var wrapperName = TypeMapper.sanitizeJavaIdentifier(methodName.substring(3, 4).toLowerCase() + methodName.substring(4));

        if (params.isEmpty()) {
            sb.openBlock("public final " + wrapperReturnType + " " + wrapperName + "()");
        } else {
            var wrapperParams = params.stream()
                    .map(p -> "Object " + TypeMapper.sanitizeJavaIdentifier(p.name()))
                    .toList();
            sb.openBlock("public final " + wrapperReturnType + " " + wrapperName + "("
                    + String.join(", ", wrapperParams) + ")");
        }

        sb.openBlock("try");

        var implCall = new StringBuilder();
        implCall.append("this.").append(methodName).append("Impl(");
        if (!params.isEmpty()) {
            var args = params.stream()
                    .map(p -> {
                        var paramName = TypeMapper.sanitizeJavaIdentifier(p.name());
                        return "(" + mapParameterType(p.type()) + ") " + paramName;
                    })
                    .toList();
            implCall.append(String.join(", ", args));
        }
        implCall.append(")");

        if (isSelfOrJp) {
            var javaRetType = mapReturnType(type);
            sb.line(javaRetType + " result = " + implCall + ";");
            sb.line("return result != null ? result : getUndefinedValue();");
        } else {
            sb.line("return " + implCall + ";");
        }

        sb.closeBlockNoNewline();
        sb.append(" catch (Exception e) {\n");
        sb.indent();
        if (isAttribute) {
            sb.line("throw new AttributeException(get_class(), \"" + attrName + "\", e);");
        } else {
            sb.line("throw new ActionException(get_class(), \"" + attrName + "\", e);");
        }
        sb.closeBlock(); // catch
        sb.closeBlock(); // method
        sb.line();
    }

    private void generateActionFinalWrapper(JavaSourceBuilder sb, Action action) {
        var isSelfOrJp = action.returnType() instanceof SelfType || action.returnType() instanceof JpRefType;
        var actionReturnType = mapReturnType(action.returnType());
        var wrapperReturnType = actionReturnType;

        var wrapperParams = action.parameters().stream()
            .map(p -> mapParameterType(p.type()) + " " + TypeMapper.sanitizeJavaIdentifier(p.name()))
                .toList();
        var paramStr = String.join(", ", wrapperParams);

        var wrapperActionName = TypeMapper.sanitizeJavaIdentifier(action.name());
        sb.openBlock("public final " + wrapperReturnType + " " + wrapperActionName + "(" + paramStr + ")");
        sb.openBlock("try");

        var implCall = new StringBuilder();
        implCall.append("this.").append(action.name()).append("Impl(");
        if (!action.parameters().isEmpty()) {
            var casts = action.parameters().stream()
                    .map(p -> toActionImplArgument(p))
                    .toList();
            implCall.append(String.join(", ", casts));
        }
        implCall.append(")");

        if (isSelfOrJp) {
            var javaRetType = actionReturnType;
            sb.line(javaRetType + " result = " + implCall + ";");
            sb.line("return result != null ? result : (" + javaRetType + ") getUndefinedValue();");
        } else if ("void".equals(actionReturnType)) {
            sb.line(implCall + ";");
            sb.line("return;");
        } else {
            sb.line("return " + implCall + ";");
        }

        sb.closeBlockNoNewline();
        sb.append(" catch (Exception e) {\n");
        sb.indent();
        sb.line("throw new ActionException(get_class(), \"" + action.name() + "\", e);");
        sb.closeBlock(); // catch
        sb.closeBlock(); // method
        sb.line();
    }

    private String toActionImplArgument(Parameter parameter) {
        var paramName = TypeMapper.sanitizeJavaIdentifier(parameter.name());
        var implParamType = mapParameterType(parameter.type());
        var wrapperParamType = mapParameterType(parameter.type());

        if (implParamType.equals(wrapperParamType)) {
            return paramName;
        }

        return "(" + implParamType + ") " + paramName;
    }

    private void generateInstanceOf(JavaSourceBuilder sb) {
        var chain = jpClass.getAncestorChain();

        if (config.hasBaseSpec()) {
            sb.line("@Override");
        }
        sb.openBlock("public boolean instanceOf(String joinpointClass)");

        var checks = chain.stream()
                .map(jp -> "\"" + jp.getName() + "\".equals(joinpointClass)")
                .toList();

        sb.line("return " + String.join("\n" + sb.getIndentStr() + "    || ", checks) + ";");
        sb.closeBlock();
    }

    private String mapReturnType(JpDataType type) {
        return mapType(type, true);
    }

    private String mapParameterType(JpDataType type) {
        return mapType(type, false);
    }

    private String mapType(JpDataType type, boolean useRootJoinPointAlias) {
        Function<String, String> jpMapper = name -> {
            if (useRootJoinPointAlias && !config.hasBaseSpec() && jpClass == model.getGlobal()
                    && (name.equals("joinpoint") || name.equals(model.getGlobal().getName()))) {
                return "Jp";
            }

            if (name.equals("joinpoint") || name.equals(model.getGlobal().getName())) {
                return TypeMapper.abstractClassName(model.getGlobal().getName())
                        + (config.hasBaseSpec() ? "<?>" : "<?, ?>");
            }
            return TypeMapper.abstractClassName(name) + "<?>";
        };

        return TypeMapper.toJavaType(
                type,
                "Self",
                jpMapper,
                TypeMapper::capitalize,
                TypeMapper::capitalize);
    }

    private String getConstructorWeaverType(JpClass jpClass) {
        return jpClass.getParent().map(parent -> parent.equals(model.getGlobal()))
                .map(isRootChild -> isRootChild ? config.weaverClassName() : config.weaverName())
                .orElse(config.weaverName());
    }

    private String getConstructorWeaverImport(JpClass jpClass) {
        if (jpClass == model.getGlobal()) {
            return config.abstractWeaverPackage() + "." + config.weaverClassName();
        }

        return jpClass.getParent().map(parent -> parent.equals(model.getGlobal()))
                .map(isRootChild -> isRootChild
                        ? config.abstractWeaverPackage() + "." + config.weaverClassName()
                : config.basePackage() + "." + config.weaverName())
            .orElse(config.basePackage() + "." + config.weaverName());
    }

    private String formatParams(List<Parameter> params) {
        return params.stream()
                .map(p -> mapParameterType(p.type()) + " " + TypeMapper.sanitizeJavaIdentifier(p.name()))
                .reduce((a, b) -> a + ", " + b)
                .orElse("");
    }

    private boolean shouldGenerateWrapper(String name, List<Parameter> params) {
        var signature = TypeMapper.memberSignature(name, params);

        if (config.baseMemberSignatures().contains(signature)) {
            return false;
        }

        var parent = jpClass.getParent().orElse(null);
        while (parent != null) {
            if (hasMatchingSignature(parent.getOwnAttributes(), signature)
                    || hasMatchingSignature(parent.getOwnActions(), signature)) {
                return false;
            }

            parent = parent.getParent().orElse(null);
        }

        return true;
    }

    private boolean hasMatchingSignature(List<?> members, String signature) {
        for (var member : members) {
            if (member instanceof Attribute attr) {
                if (TypeMapper.memberSignature(attr.name(), attr.parameters()).equals(signature)) {
                    return true;
                }
                continue;
            }

            if (member instanceof Action action
                    && TypeMapper.memberSignature(action.name(), action.parameters()).equals(signature)) {
                return true;
            }
        }

        return false;
    }
}
