package org.lara.weavergen2.generator;

import org.lara.langspec2.model.*;
import org.lara.langspec2.types.JpDataType;
import org.lara.langspec2.types.JpDataType.*;
import org.lara.weavergen2.java.JavaSourceBuilder;
import org.lara.weavergen2.java.TypeMapper;

import java.util.*;
import java.util.function.Function;

/**
 * Generates an abstract join point class from a {@link JpClass}.
 * <p>
 * This generates the new-style abstract classes that use provider dispatch for
 * inherited methods instead of delegation chains.
 */
public final class AbstractJpGenerator {

    private final JpClass jpClass;
    private final WeaverModel model;
    private final GeneratorConfig config;
    private final boolean isRoot;

    public AbstractJpGenerator(JpClass jpClass, WeaverModel model, GeneratorConfig config) {
        this.jpClass = jpClass;
        this.model = model;
        this.config = config;
        this.isRoot = jpClass.getParent().isEmpty() || jpClass == model.getGlobal();
    }

    public String generate() {
        var sb = new JavaSourceBuilder();
        var standaloneMode = !config.hasBaseSpec();

        // Package
        sb.line("package " + config.joinPointPackage() + ";");
        sb.line();

        // Imports
        generateImports(sb);
        sb.line();

        // Class declaration
        var className = TypeMapper.abstractClassName(jpClass.getName());
        String superClass = null;
        if (!standaloneMode) {
            if (isRoot) {
                superClass = config.userAbstractClassName() + "<Self>";
            } else {
                superClass = TypeMapper.abstractClassName(jpClass.getParent().get().getName()) + "<Self>";
            }
        }

        sb.line("/**");
        sb.line(" * Auto-generated abstract class for the {@code " + jpClass.getName() + "} join point.");
        sb.line(" * <p>");
        sb.line(" * This class is generated by WeaverGen2 and should not be edited manually.");
        sb.line(" */");
        if (superClass == null) {
            sb.openBlock("public abstract class " + className + "<Self extends " + className + "<Self>>");
        } else {
            sb.openBlock("public abstract class " + className + "<Self extends " + className + "<Self>> extends "
                    + superClass);
        }
        sb.line();

        if (!standaloneMode) {
            // Constructor
            sb.openBlock("public " + className + "(" + config.weaverClassName() + " weaver)");
            sb.line("super(weaver);");
            sb.closeBlock();
            sb.line();
        }

        // Own attributes
        for (var attr : jpClass.getOwnAttributes()) {
            generateOwnAttribute(sb, attr, standaloneMode);
        }

        // Own actions
        for (var action : jpClass.getOwnActions()) {
            generateOwnAction(sb, action, standaloneMode);
        }

        // Inherited methods
        if (!isRoot) {
            var inherited = collectInheritedAttributesWithOwner();
            for (var entry : inherited) {
                generateInheritedAttribute(sb, entry.attr, entry.owner, standaloneMode);
            }

            var inheritedActions = collectInheritedActionsWithOwner();
            for (var entry : inheritedActions) {
                generateInheritedAction(sb, entry.action, entry.owner, standaloneMode);
            }
        }

        // get_class()
        if (config.hasBaseSpec()) {
            sb.line("@Override");
        }
        sb.openBlock("public String get_class()");
        sb.line("return \"" + jpClass.getName() + "\";");
        sb.closeBlock();
        sb.line();

        // instanceOf()
        generateInstanceOf(sb);

        sb.closeBlock(); // class

        return sb.toString();
    }

    private void generateImports(JavaSourceBuilder sb) {
        var standaloneMode = !config.hasBaseSpec();

        if (!standaloneMode) {
            sb.line("import " + config.baseJoinPointPackage() + ".*;");
            sb.line("import " + config.abstractWeaverPackage() + "." + config.weaverClassName() + ";");
            if (jpClass == model.getGlobal()) {
                sb.line("import " + config.abstractsPackage() + "." + config.userAbstractClassName() + ";");
            }
        }
        if (!model.getTypeDefs().isEmpty()) {
            sb.line("import " + config.entitiesPackage() + ".*;");
        }
        if (!model.getEnumDefs().isEmpty()) {
            sb.line("import " + config.enumsPackage() + ".*;");
        }
        if (!standaloneMode && !config.providerPackage().equals(config.joinPointPackage())) {
            sb.line("import " + config.providerPackage() + ".*;");
        }
        if (!standaloneMode) {
            sb.line("import org.lara.interpreter.exception.ActionException;");
            sb.line("import org.lara.interpreter.exception.AttributeException;");
            sb.line();
            sb.line("import java.util.*;");
        }
    }

    private void generateOwnAttribute(JavaSourceBuilder sb, Attribute attr, boolean standaloneMode) {
        var javaRetType = mapType(attr.type());
        var methodName = "get" + TypeMapper.capitalize(attr.name());

        var implMethodName = standaloneMode ? methodName : methodName + "Impl";

        if (attr.parameters().isEmpty()) {
            sb.line("public abstract " + javaRetType + " " + implMethodName + "();");
        } else {
            var params = formatParams(attr.parameters());
            sb.line("public abstract " + javaRetType + " " + implMethodName + "(" + params + ");");
        }
        sb.line();

        if (!standaloneMode) {
            // Final wrapper
            generateFinalWrapper(sb, attr.name(), methodName, attr.type(), attr.parameters(), true);
        }
    }

    private void generateOwnAction(JavaSourceBuilder sb, Action action, boolean standaloneMode) {
        var javaRetType = mapType(action.returnType());
        var methodName = action.name();
        var implMethodName = standaloneMode ? methodName : methodName + "Impl";

        var paramStr = formatParams(action.parameters());

        if (standaloneMode) {
            sb.line("public abstract " + javaRetType + " " + implMethodName + "(" + paramStr + ");");
        } else {
            // Impl method (default: throws)
            sb.openBlock("public " + javaRetType + " " + implMethodName + "(" + paramStr + ")");
            sb.line("throw new UnsupportedOperationException(get_class() + \": Action " + action.name()
                    + " not implemented\");");
            sb.closeBlock();
        }
        sb.line();

        if (!standaloneMode) {
            // Final wrapper
            generateActionFinalWrapper(sb, action);
        }
    }

    private void generateInheritedAttribute(JavaSourceBuilder sb, Attribute attr, JpClass owner,
            boolean standaloneMode) {
        if (standaloneMode) {
            return;
        }

        var javaRetType = mapType(attr.type());
        var methodName = "get" + TypeMapper.capitalize(attr.name());
        var providerDefClass = TypeMapper.providerDefName(owner.getName());
        var isSelf = attr.type() instanceof SelfType;

        sb.line("@SuppressWarnings(\"unchecked\")");
        sb.line("@Override");
        if (attr.parameters().isEmpty()) {
            sb.openBlock("public " + javaRetType + " " + methodName + "Impl()");
            if (isSelf) {
                sb.line("return (Self) provider(" + providerDefClass + ".class)." + methodName + "Impl(this);");
            } else {
                sb.line("return provider(" + providerDefClass + ".class)." + methodName + "Impl(this);");
            }
        } else {
            var params = formatParams(attr.parameters());
            var argNames = attr.parameters().stream()
                    .map(Parameter::name)
                    .map(TypeMapper::sanitizeJavaIdentifier)
                    .toList();
            sb.openBlock("public " + javaRetType + " " + methodName + "Impl(" + params + ")");
            if (isSelf) {
                sb.line("return (Self) provider(" + providerDefClass + ".class)." + methodName + "Impl(this, "
                        + String.join(", ", argNames) + ");");
            } else {
                sb.line("return provider(" + providerDefClass + ".class)." + methodName + "Impl(this, "
                        + String.join(", ", argNames) + ");");
            }
        }
        sb.closeBlock();
        sb.line();
    }

    private void generateInheritedAction(JavaSourceBuilder sb, Action action, JpClass owner, boolean standaloneMode) {
        if (standaloneMode) {
            return;
        }

        var javaRetType = mapType(action.returnType());
        var methodName = action.name();
        var providerDefClass = TypeMapper.providerDefName(owner.getName());
        var isSelfReturn = "Self".equals(javaRetType) || "Self[]".equals(javaRetType);

        var params = formatParams(action.parameters());
        var argNames = action.parameters().stream()
                .map(Parameter::name)
                .map(TypeMapper::sanitizeJavaIdentifier)
                .toList();

        sb.line("@SuppressWarnings(\"unchecked\")");
        sb.line("@Override");
        sb.openBlock("public " + javaRetType + " " + methodName + "Impl(" + params + ")");
        var argsStr = argNames.isEmpty() ? "this" : "this, " + String.join(", ", argNames);
        if ("void".equals(javaRetType)) {
            sb.line("provider(" + providerDefClass + ".class)." + methodName + "Impl(" + argsStr + ");");
        } else {
            if (isSelfReturn) {
                sb.line("return (" + javaRetType + ") provider(" + providerDefClass + ".class)." + methodName + "Impl("
                        + argsStr + ");");
            } else {
                sb.line("return provider(" + providerDefClass + ".class)." + methodName + "Impl(" + argsStr + ");");
            }
        }
        sb.closeBlock();
        sb.line();
    }

    private void generateFinalWrapper(JavaSourceBuilder sb, String attrName, String methodName,
            JpDataType type, List<Parameter> params, boolean isAttribute) {
        var isBaseAttribute = config.baseAttributeNames().contains(attrName);
        var isSelfOrJp = type instanceof SelfType || type instanceof JpRefType;
        var wrapperReturnType = isBaseAttribute ? mapType(type) : "Object";
        var wrapperName = isBaseAttribute
                ? TypeMapper.sanitizeJavaIdentifier(attrName.startsWith("get") ? attrName : methodName)
                : TypeMapper.sanitizeJavaIdentifier(methodName.substring(3, 4).toLowerCase() + methodName.substring(4));

        if (params.isEmpty()) {
            sb.openBlock("public final " + wrapperReturnType + " " + wrapperName + "()");
        } else {
            var wrapperParams = params.stream()
                    .map(p -> (isBaseAttribute ? mapType(p.type()) + " " : "Object ")
                            + TypeMapper.sanitizeJavaIdentifier(p.name()))
                    .toList();
            sb.openBlock("public final " + wrapperReturnType + " " + wrapperName + "("
                    + String.join(", ", wrapperParams) + ")");
        }

        sb.openBlock("try");

        var implCall = new StringBuilder();
        implCall.append("this.").append(methodName).append("Impl(");
        if (!params.isEmpty()) {
            var args = params.stream()
                    .map(p -> {
                        var paramName = TypeMapper.sanitizeJavaIdentifier(p.name());
                        if (isBaseAttribute) {
                            return paramName;
                        }
                        return "(" + TypeMapper.boxed(mapType(p.type())) + ") " + paramName;
                    })
                    .toList();
            implCall.append(String.join(", ", args));
        }
        implCall.append(")");

        if (isSelfOrJp && !isBaseAttribute) {
            var javaRetType = mapType(type);
            sb.line(javaRetType + " result = " + implCall + ";");
            sb.line("return result != null ? result : getUndefinedValue();");
        } else {
            sb.line("return " + implCall + ";");
        }

        sb.closeBlockNoNewline();
        sb.append(" catch (Exception e) {\n");
        sb.indent();
        if (isAttribute) {
            sb.line("throw new AttributeException(get_class(), \"" + attrName + "\", e);");
        } else {
            sb.line("throw new ActionException(get_class(), \"" + attrName + "\", e);");
        }
        sb.closeBlock(); // catch
        sb.closeBlock(); // method
        sb.line();
    }

    private void generateActionFinalWrapper(JavaSourceBuilder sb, Action action) {
        var isSelfOrJp = action.returnType() instanceof SelfType || action.returnType() instanceof JpRefType;
        var actionReturnType = mapType(action.returnType());
        var wrapperReturnType = actionReturnType;

        var wrapperParams = action.parameters().stream()
                .map(p -> mapType(p.type()) + " " + TypeMapper.sanitizeJavaIdentifier(p.name()))
                .toList();
        var paramStr = String.join(", ", wrapperParams);

        var wrapperActionName = TypeMapper.sanitizeJavaIdentifier(action.name());
        sb.openBlock("public final " + wrapperReturnType + " " + wrapperActionName + "(" + paramStr + ")");
        sb.openBlock("try");

        var implCall = new StringBuilder();
        implCall.append("this.").append(action.name()).append("Impl(");
        if (!action.parameters().isEmpty()) {
            var casts = action.parameters().stream()
                    .map(p -> toActionImplArgument(p))
                    .toList();
            implCall.append(String.join(", ", casts));
        }
        implCall.append(")");

        if (isSelfOrJp) {
            var javaRetType = actionReturnType;
            sb.line(javaRetType + " result = " + implCall + ";");
            sb.line("return result != null ? result : (" + javaRetType + ") getUndefinedValue();");
        } else if ("void".equals(actionReturnType)) {
            sb.line(implCall + ";");
            sb.line("return;");
        } else {
            sb.line("return " + implCall + ";");
        }

        sb.closeBlockNoNewline();
        sb.append(" catch (Exception e) {\n");
        sb.indent();
        sb.line("throw new ActionException(get_class(), \"" + action.name() + "\", e);");
        sb.closeBlock(); // catch
        sb.closeBlock(); // method
        sb.line();
    }

    private String toActionImplArgument(Parameter parameter) {
        var paramName = TypeMapper.sanitizeJavaIdentifier(parameter.name());
        var implParamType = mapType(parameter.type());
        var wrapperParamType = mapType(parameter.type());

        if (implParamType.equals(wrapperParamType)) {
            return paramName;
        }

        return "(" + implParamType + ") " + paramName;
    }

    private void generateInstanceOf(JavaSourceBuilder sb) {
        var chain = jpClass.getAncestorChain();

        if (config.hasBaseSpec()) {
            sb.line("@Override");
        }
        sb.openBlock("public boolean instanceOf(String joinpointClass)");

        var checks = chain.stream()
                .map(jp -> "\"" + jp.getName() + "\".equals(joinpointClass)")
                .toList();

        sb.line("return " + String.join("\n" + sb.getIndentStr() + "    || ", checks) + ";");
        sb.closeBlock();
    }

    private String mapType(JpDataType type) {
        Function<String, String> jpMapper = name -> {
            if (name.equals("joinpoint") || name.equals(model.getGlobal().getName())) {
                return TypeMapper.abstractClassName(model.getGlobal().getName()) + "<?>";
            }
            return TypeMapper.abstractClassName(name) + "<?>";
        };

        return TypeMapper.toJavaType(
                type,
                "Self",
                jpMapper,
                TypeMapper::capitalize,
                TypeMapper::capitalize);
    }

    private String formatParams(List<Parameter> params) {
        return params.stream()
                .map(p -> mapType(p.type()) + " " + TypeMapper.sanitizeJavaIdentifier(p.name()))
                .reduce((a, b) -> a + ", " + b)
                .orElse("");
    }

    record InheritedAttr(Attribute attr, JpClass owner) {
    }

    record InheritedAction(Action action, JpClass owner) {
    }

    /**
     * Collects all inherited attributes paired with their declaring owner,
     * excluding this JP's own attributes.
     */
    private List<InheritedAttr> collectInheritedAttributesWithOwner() {
        var result = new ArrayList<InheritedAttr>();
        var seenSignatures = new LinkedHashSet<MemberSignature>();

        // Own members override inherited ones with the same signature.
        for (var ownAttr : jpClass.getOwnAttributes()) {
            seenSignatures.add(memberSignature(ownAttr.name(), ownAttr.parameters()));
        }

        var current = jpClass.getParent().orElse(null);
        while (current != null) {
            for (var attr : current.getOwnAttributes()) {
                var signature = memberSignature(attr.name(), attr.parameters());
                if (!seenSignatures.add(signature)) {
                    continue;
                }
                result.add(new InheritedAttr(attr, current));
            }
            current = current.getParent().orElse(null);
        }
        return result;
    }

    private List<InheritedAction> collectInheritedActionsWithOwner() {
        var result = new ArrayList<InheritedAction>();
        var seenSignatures = new LinkedHashSet<MemberSignature>();

        // Own members override inherited ones with the same signature.
        for (var ownAction : jpClass.getOwnActions()) {
            seenSignatures.add(memberSignature(ownAction.name(), ownAction.parameters()));
        }

        var current = jpClass.getParent().orElse(null);
        while (current != null) {
            for (var action : current.getOwnActions()) {
                var signature = memberSignature(action.name(), action.parameters());
                if (!seenSignatures.add(signature)) {
                    continue;
                }
                result.add(new InheritedAction(action, current));
            }
            current = current.getParent().orElse(null);
        }
        return result;
    }

    private MemberSignature memberSignature(String name, List<Parameter> parameters) {
        var parameterTypes = parameters.stream().map(Parameter::type).toList();
        return new MemberSignature(name, parameterTypes);
    }

    record MemberSignature(String name, List<JpDataType> parameterTypes) {
    }
}
