package org.lara.weavergen2.generator;

import org.lara.langspec2.dsl.WeaverSpec;
import org.lara.langspec2.model.*;
import org.lara.langspec2.types.JpDataType;
import org.lara.langspec2.types.JpDataType.*;
import org.lara.weavergen2.java.JavaSourceBuilder;
import org.lara.weavergen2.java.TypeMapper;

import java.nio.file.*;
import java.util.*;
import java.util.function.Function;
import java.util.regex.*;

/**
 * Generates an abstract join point class from a {@link JpClass}.
 * <p>
 * This generates abstract classes where inherited methods are resolved through
 * the Java class hierarchy.
 */
public final class AbstractJpGenerator {

    private final JpClass jpClass;
    private final WeaverModel model;
    private final GeneratorConfig config;

    public AbstractJpGenerator(JpClass jpClass, WeaverModel model, GeneratorConfig config) {
        this.jpClass = jpClass;
        this.model = model;
        this.config = config;
    }

    public String generate() {
        var sb = new JavaSourceBuilder();
        var standaloneMode = !config.hasBaseSpec();

        // Package
        sb.line("package " + config.joinPointPackage() + ";");
        sb.line();

        // Imports
        generateImports(sb);

        // Class declaration
        var className = TypeMapper.abstractClassName(jpClass.getName());
        String superClass = null;
        if (!standaloneMode) {
            if (jpClass == model.getGlobal()) {
                superClass = getConcreteSuperclass(jpClass) + "<Self, " + className + "<?>>";
            } else {
                superClass = getConcreteSuperclass(jpClass) + "<Self>";
            }
        }

        sb.line("/**");
        sb.line(" * Auto-generated abstract class for the {@code " + jpClass.getName() + "} join point.");
        sb.line(" * <p>");
        sb.line(" * This class is generated by WeaverGen2 and should not be edited manually.");
        sb.line(" */");
        if (superClass == null) {
            sb.openBlock("public abstract class " + className + "<Self extends " + className + "<Self, Jp>, Jp extends "
                    + className + "<?, Jp>>");
        } else {
            sb.openBlock("public abstract class " + className + "<Self extends " + className + "<Self>> extends "
                    + superClass);
        }
        sb.line();

        if (standaloneMode) {
            // Constructor and getWeaverEngine()
            sb.line("private final WeaverEngine weaver;");
            sb.line();
            sb.openBlock("protected " + className + "(WeaverEngine weaver)");
            sb.line("this.weaver = weaver;");
            sb.closeBlock();
            sb.line();
            sb.openBlock("public WeaverEngine getWeaverEngine()");
            sb.line("return weaver;");
            sb.closeBlock();
            sb.line();
        } else {
            // Constructor
            var nodeType = simpleClassName(config.nodeType());
            if (hasConcreteSuperclassNodeTypeCast(jpClass)) {
                nodeType = getConcreteSuperclassNodeType(jpClass);
            }

            var constructorWeaverType = getConstructorWeaverType(jpClass);
            if (jpClass == model.getGlobal()) {

                sb.line("/**");
                sb.line(" *  FIXME: This should be a private field");
                sb.line(" */ ");
                sb.line("@Deprecated");
                sb.line("protected " + nodeType + " node;");
                sb.line();
                sb.openBlock("public " + className + "(" + nodeType + " node, "
                        + config.weaverClassName() + " weaver)");
                sb.line("super(weaver);");
                sb.line("this.node = node;");
                sb.closeBlock();
                sb.line();

                sb.openBlock("public " + nodeType + " getNodeImpl()");
                sb.line("return node;");
                sb.closeBlock();
                sb.line();
            } else {
                sb.openBlock("public " + className + "(" + nodeType + " node, " + constructorWeaverType + " weaver)");
                sb.line("super(node, weaver);");
                sb.closeBlock();
                sb.line();
            }
        }

        // Own attributes
        for (var attr : jpClass.getOwnAttributes()) {
            generateOwnAttribute(sb, attr);
        }

        // Own actions
        for (var action : jpClass.getOwnActions()) {
            generateOwnAction(sb, action);
        }

        // get_class()
        if (!standaloneMode) {
            sb.line("@Override");
        }
        sb.openBlock("public String get_class()");
        sb.line("return \"" + jpClass.getName() + "\";");
        sb.closeBlock();
        sb.line();

        // instanceOf()
        if (!standaloneMode) {
            generateInstanceOf(sb);
        }

        // Array factories and undefined value
        if (standaloneMode) {
            sb.line("protected abstract IntFunction<Self[]> selfTypeArrayFactory();");
            sb.line();
            sb.line("protected abstract IntFunction<Jp[]> jpTypeArrayFactory();");
            sb.line();
            sb.openBlock("public static Object getUndefinedValue()");
            sb.line("return UndefinedValue.getUndefined();");
            sb.closeBlock();
        } else {
            sb.line();
            sb.line("@SuppressWarnings(\"unchecked\")");
            sb.line("@Override");
            sb.openBlock("protected IntFunction<Self[]> selfTypeArrayFactory()");
            sb.line("return size -> (Self[]) new " + className + "[size];");
            sb.closeBlock();
            if (jpClass == model.getGlobal()) {
                sb.line();
                sb.line("@Override");
                sb.openBlock("protected final IntFunction<" + className + "<?>[]> jpTypeArrayFactory()");
                sb.line("return size -> new " + className + "[size];");
                sb.closeBlock();
            }
        }

        sb.closeBlock(); // class

        return sb.toString();
    }

    private void generateImports(JavaSourceBuilder sb) {
        var standaloneMode = !config.hasBaseSpec();

        if (standaloneMode) {
            sb.line("import org.lara.interpreter.weaver.interf.WeaverEngine;");
        }
        if (!standaloneMode) {
            sb.line("import " + config.baseJoinPointPackage() + ".*;");
            sb.line("import " + getConstructorWeaverImport(jpClass) + ";");
            var parentConcreteImport = getConcreteSuperclassImport(jpClass);
            if (parentConcreteImport.isPresent()) {
                sb.line("import " + parentConcreteImport.get() + ";");
            }
            sb.line("import " + config.nodeType() + ";");
            var concreteSuperclassNodeTypeImport = getConcreteSuperclassNodeTypeImport(jpClass);
            if (concreteSuperclassNodeTypeImport.isPresent()
                    && !concreteSuperclassNodeTypeImport.get().equals(config.nodeType())) {
                sb.line("import " + concreteSuperclassNodeTypeImport.get() + ";");
            }
        }
        if (!model.getTypeDefs().isEmpty()) {
            sb.line("import " + config.entitiesPackage() + ".*;");
        }
        if (!model.getEnumDefs().isEmpty()) {
            sb.line("import " + config.enumsPackage() + ".*;");
        }
        if (jpClass.getOwnActions().size() > 0) {
            sb.line("import org.lara.interpreter.exception.ActionException;");
        }
        if (jpClass.getOwnAttributes().size() > 0) {
            sb.line("import org.lara.interpreter.exception.AttributeException;");
        }
        if (jpClass.getOwnActions().size() > 0 || jpClass.getOwnAttributes().size() > 0) {
            sb.line("import org.lara.interpreter.weaver.interf.events.Stage;");
            sb.line("import java.util.Optional;");
        }
        sb.line();
        sb.line("import java.util.*;");
        sb.line("import java.util.function.IntFunction;");
        if (standaloneMode) {
            sb.line("import pt.up.fe.specs.jsengine.node.UndefinedValue;");
        }
        sb.line();
    }

    private String simpleClassName(String fullyQualifiedName) {
        var lastDot = fullyQualifiedName.lastIndexOf('.');
        return lastDot < 0 ? fullyQualifiedName : fullyQualifiedName.substring(lastDot + 1);
    }

    private String getConcreteSuperclass(JpClass jpClass) {
        if (jpClass == model.getGlobal()) {
            return config.baseJoinPointClass();
        }

        var parent = jpClass.getParent().orElseThrow();
        return concreteClassName(parent);
    }

    private Optional<String> getConcreteSuperclassImport(JpClass jpClass) {
        if (jpClass == model.getGlobal()) {
            return Optional.empty();
        }

        var parent = jpClass.getParent().orElseThrow();
        var concretePackage = concretePackage(parent);
        var concreteClass = concreteClassName(parent);

        return Optional.of(concretePackage + "." + concreteClass);
    }

    private String getConcreteSuperclassNodeType(JpClass jpClass) {
        var nodeTypeImport = getConcreteSuperclassNodeTypeImport(jpClass)
                .orElseThrow(() -> new IllegalStateException(
                        "Could not resolve constructor node type for join point '" + jpClass.getName() + "'"));

        return simpleClassName(nodeTypeImport);
    }

    private Optional<String> getConcreteSuperclassNodeTypeImport(JpClass jpClass) {
        if (jpClass == model.getGlobal()
                || jpClass.getParent().map(parent -> parent.equals(model.getGlobal())).orElse(false)) {
            return Optional.of(config.nodeType());
        }

        var concreteSuperclassImport = getConcreteSuperclassImport(jpClass)
                .orElseThrow(() -> new IllegalStateException(
                        "Could not resolve concrete superclass for join point '" + jpClass.getName() + "'"));

        try {
            var sourceFile = resolveSourceFile(concreteSuperclassImport)
                    .orElseThrow(
                            () -> new IllegalStateException("Could not locate source file for concrete superclass '"
                                    + concreteSuperclassImport + "' while generating join point '" + jpClass.getName()
                                    + "'"));

            var source = Files.readString(sourceFile);
            var concreteSuperclassName = simpleClassName(concreteSuperclassImport);
            var constructorMatcher = Pattern.compile("public\\s+" + Pattern.quote(concreteSuperclassName)
                    + "\\s*\\(([^)]*)\\)", Pattern.DOTALL).matcher(source);

            if (!constructorMatcher.find()) {
                throw new IllegalStateException("Could not find constructor signature for '" + concreteSuperclassImport
                        + "' in source file '" + sourceFile + "'");
            }

            var parameters = constructorMatcher.group(1).trim();
            var firstParameter = parameters.split(",", 2)[0].trim();
            var firstSpace = firstParameter.lastIndexOf(' ');

            if (firstSpace < 0) {
                throw new IllegalStateException("Could not parse first constructor parameter of '"
                        + concreteSuperclassImport + "' from source file '" + sourceFile + "'");
            }

            var nodeTypeSimpleName = firstParameter.substring(0, firstSpace).trim();
            return Optional.of(resolveNodeTypeImport(source, sourceFile, concreteSuperclassImport, nodeTypeSimpleName));
        } catch (java.io.IOException e) {
            throw new IllegalStateException("Could not read source file for concrete superclass '"
                    + concreteSuperclassImport + "' while generating join point '" + jpClass.getName() + "'", e);
        }
    }

    private Optional<Path> resolveSourceFile(String fullyQualifiedClassName) {
        var relativePath = fullyQualifiedClassName.replace('.', '/') + ".java";
        var sourceRoots = List.of("src", "src-java", "src/main/java");

        for (var sourceRoot : sourceRoots) {
            var sourceFile = Path.of(System.getProperty("user.dir"), sourceRoot).resolve(relativePath);
            if (Files.exists(sourceFile)) {
                return Optional.of(sourceFile);
            }
        }

        return Optional.empty();
    }

    private String resolveNodeTypeImport(String source,
            Path sourceFile,
            String concreteSuperclassImport,
            String nodeTypeSimpleName) {

        if (nodeTypeSimpleName.contains(".")) {
            return nodeTypeSimpleName;
        }

        if (TypeMapper.isPrimitive(nodeTypeSimpleName)) {
            return nodeTypeSimpleName;
        }

        try {
            Class.forName("java.lang." + nodeTypeSimpleName);
            return "java.lang." + nodeTypeSimpleName;
        } catch (ClassNotFoundException e) {
            // Not a java.lang type, continue resolving from imports below.
        }

        var importMatcher = Pattern.compile("^import\\s+([^;]+\\." + Pattern.quote(nodeTypeSimpleName) + ");$",
                Pattern.MULTILINE).matcher(source);

        if (importMatcher.find()) {
            return importMatcher.group(1);
        }

        throw new IllegalStateException("Could not resolve import for constructor node type '" + nodeTypeSimpleName
                + "' in concrete superclass '" + concreteSuperclassImport + "' from source file '" + sourceFile + "'");
    }

    private boolean hasConcreteSuperclassNodeTypeCast(JpClass jpClass) {
        return jpClass.getParent().map(parent -> !parent.equals(model.getGlobal())).orElse(false);
    }

    private String concreteClassName(JpClass jpClass) {
        return "Cxx" + TypeMapper.capitalize(jpClass.getName());
    }

    private String concretePackage(JpClass jpClass) {
        var concreteBasePackage = config.basePackage() + ".joinpoints";

        if (isCilkBranch(jpClass)) {
            return concreteBasePackage + ".cilk";
        }

        if (isTypeBranch(jpClass)) {
            return concreteBasePackage + ".types";
        }

        return concreteBasePackage;
    }

    private boolean isTypeBranch(JpClass jpClass) {
        var typeRoot = findJpClass("type");
        return typeRoot != null && jpClass.isOrExtends(typeRoot);
    }

    private boolean isCilkBranch(JpClass jpClass) {
        return jpClass.getName().toLowerCase(Locale.ROOT).startsWith("cilk");
    }

    private JpClass findJpClass(String name) {
        return model.getAllJpClasses().stream()
                .filter(jp -> jp.getName().equals(name))
                .findFirst()
                .orElse(null);
    }

    private void generateOwnAttribute(JavaSourceBuilder sb, Attribute attr) {
        generateOwnMethod(sb, attr.name(), attr.type(), attr.parameters(), true);
    }

    private void generateOwnAction(JavaSourceBuilder sb, Action action) {
        generateOwnMethod(sb, action.name(), action.returnType(), action.parameters(), false);
    }

    private void generateOwnMethod(JavaSourceBuilder sb, String methodName, JpDataType returnType, List<Parameter> parameters, boolean isAttribute) {
        var javaRetType = mapReturnType(returnType);
        var finalName = isAttribute ? ("get" + TypeMapper.capitalize(methodName)) : methodName;
        var implMethodName = finalName + "Impl";

        var params = formatImplParams(parameters);

        sb.line("public abstract " + javaRetType + " " + implMethodName + "(" + params + ");");
        sb.line();

        if (shouldGenerateWrapper(methodName, parameters)) {
            generateFinalWrapper(sb, methodName, finalName, returnType, parameters, isAttribute);
        }
    }

    private void generateFinalWrapper(JavaSourceBuilder sb, String attrName, String methodName,
            JpDataType type, List<Parameter> params, boolean isAttribute) {
        var isReferenceType = type instanceof SelfType || type instanceof JpRefType || type instanceof ReferenceType;
        var wrapperReturnType = mapPublicReturnType(type);
        var wrapperName = TypeMapper.sanitizeJavaIdentifier(attrName);
        var methodClass = isAttribute ? "Attribute" : "Action";

        sb.line("@Deprecated");
        if (params.isEmpty()) {
            sb.openBlock("public final " + wrapperReturnType + " " + wrapperName + "()");
        } else {
            var wrapperParams = formatPublicParams(params);
            sb.openBlock("public final " + wrapperReturnType + " " + wrapperName + "("
                    + String.join(", ", wrapperParams) + ")");
        }

        sb.openBlock("try");

        var eventTriggerArgsString = buildEventTriggerArgsString(params);

        sb.openBlock("if(getWeaverEngine().hasListeners())");
        sb.line("getWeaverEngine().getEventTrigger().trigger" + methodClass + "(Stage.BEGIN, this, \"" + attrName + "\", Optional.empty()" + eventTriggerArgsString + ");");
        sb.closeBlock();

        var implCall = new StringBuilder();
        implCall.append("this.").append(methodName).append("Impl(");
        if (!params.isEmpty()) {
            var args = params.stream()
                    .map(p -> {
                        var paramName = TypeMapper.sanitizeJavaIdentifier(p.name());
                        return toImplArgument(p.type(), paramName);
                    })
                    .toList();
            implCall.append(String.join(", ", args));
        }
        implCall.append(")");

        if (type == WeaverSpec.VOID) {
            sb.line(implCall + ";");
        } else {
            if (isEnumLike(type)) {
                sb.line(wrapperReturnType + " result = " + toPublicEnumReturnExpression(type, implCall) + ";");
            } else {
                var javaRetType = mapReturnType(type);
                sb.line(javaRetType + " result = " + implCall + ";");
            }
        }

        sb.openBlock("if(getWeaverEngine().hasListeners())");
        sb.line("getWeaverEngine().getEventTrigger().trigger" + methodClass + "(Stage.END, this, \"" + attrName + "\", " + ((type == WeaverSpec.VOID) ? "Optional.empty()" : "Optional.ofNullable(result)") + eventTriggerArgsString + ");");
        sb.closeBlock();

        if (type == WeaverSpec.VOID) {
            sb.line("return;");
        } else if (isReferenceType) {
            sb.line("return result != null ? result : getUndefinedValue();");
        } else {
            sb.line("return result;");
        }

        sb.closeBlockNoNewline();
        sb.append(" catch (Exception e) {\n");
        sb.indent();
        sb.line("throw new " + methodClass + "Exception(get_class(), \"" + attrName + "\", e);");
        sb.closeBlock(); // catch
        sb.closeBlock(); // method
        sb.line();
    }

    private String buildEventTriggerArgsString(List<Parameter> params) {
        if (params.isEmpty()) {
            return "";
        }
        return ", " + String.join(", ",
                params.stream()
                        .map(p -> (p.type() instanceof ArrayType ? "(Object) " : "") + TypeMapper.sanitizeJavaIdentifier(p.name()))
                        .toList());
    }

    private String toImplArgument(JpDataType type, String paramName) {
        if (type instanceof DirectType) {
            return paramName;
        }

        if (type == WeaverSpec.OBJECT) {
            return paramName;
        }

        if (type instanceof EnumRefType ref) {
            return TypeMapper.capitalize(ref.enumName()) + ".fromDisplay(" + paramName + ")";
        }

        if (type instanceof ArrayType arrayType) {
            if (arrayType.element() instanceof DirectType) {
                return paramName;
            }
            if (arrayType.element() == WeaverSpec.OBJECT) {
                return paramName;
            }

            if (isEnumLike(arrayType.element())) {
                return toImplEnumArrayArgument(arrayType, paramName);
            }

            String castType = mapArrayCastType(arrayType);
            switch (castType) {
                case "Jp":
                    castType = "jpTypeArrayFactory()";
                    break;
                case "Self":
                    castType = "selfTypeArrayFactory()";
                    break;
                default:
                    castType += ".class";
                    break;
            }

            return "pt.up.fe.specs.util.SpecsCollections.cast(" + paramName + ", " + castType + ")";
        }

        if (type instanceof ParameterizedType parameterizedType && parameterizedType.base() instanceof DirectType) {
            return paramName;
        }

        return "(" + mapParameterType(type) + ") " + paramName;
    }

    private String toImplEnumArrayArgument(ArrayType arrayType, String sourceExpression) {
        var element = arrayType.element();

        if (element instanceof EnumRefType ref) {
            var enumType = TypeMapper.capitalize(ref.enumName());
            return "Arrays.stream(" + sourceExpression + ")"
                    + ".map(" + enumType + "::fromDisplay)"
                    + ".toArray(" + enumType + "[]::new)";
        }

        if (element instanceof ArrayType innerArray) {
            var lambdaVar = "value";
            var innerExpression = toImplEnumArrayArgument(innerArray, lambdaVar);
            return "Arrays.stream(" + sourceExpression + ")"
                    + ".map(" + lambdaVar + " -> " + innerExpression + ")"
                    + ".toArray(" + mapParameterType(arrayType) + "::new)";
        }

        throw new IllegalArgumentException("Unsupported enum array type: " + arrayType);
    }

    private void generateInstanceOf(JavaSourceBuilder sb) {
        var chain = jpClass.getAncestorChain();

        sb.line("@Override");
        sb.openBlock("public boolean instanceOfImpl(String joinpointClassname)");

        var checks = chain.stream()
                .map(jp -> "\"" + jp.getName() + "\".equals(joinpointClassname)")
                .toList();

        sb.line("return " + String.join("\n" + sb.getIndentStr() + "    || ", checks) + ";");
        sb.closeBlock();
    }

    private String mapReturnType(JpDataType type) {
        return mapType(type);
    }

    private String mapParameterType(JpDataType type) {
        return mapType(type);
    }

    private String mapPublicReturnType(JpDataType type) {
        if (type instanceof DirectType primitiveType) {
            return primitiveType.name();
        }
        if (type instanceof ReferenceType) {
            return "Object";
        }
        if (type instanceof EnumRefType) {
            return "String";
        }
        if (type instanceof ArrayType arrayType) {
            return mapPublicReturnType(arrayType.element()) + "[]";
        }

        return "Object";
    }

    private String mapPublicParameterType(JpDataType type) {
        if (type instanceof DirectType primitiveType) {
            return primitiveType.name();
        }

        if (type instanceof ReferenceType referenceType) {
            return referenceType.name();
        }

        if (type instanceof EnumRefType) {
            return "String";
        }

        if (type instanceof ArrayType arrayType) {
            return mapPublicParameterType(arrayType.element()) + "[]";
        }

        if (type instanceof ParameterizedType parameterizedType && parameterizedType.base() instanceof DirectType) {
            return mapType(parameterizedType);
        }

        return "Object";
    }

    private String formatImplParams(List<Parameter> params) {
        return params.stream()
                .map(p -> mapParameterType(p.type()) + " " + TypeMapper.sanitizeJavaIdentifier(p.name()))
                .reduce((a, b) -> a + ", " + b)
                .orElse("");
    }

    private List<String> formatPublicParams(List<Parameter> params) {
        return params.stream()
                .map(p -> String.join(" ", mapPublicParameterType(p.type()),
                        TypeMapper.sanitizeJavaIdentifier(p.name())))
                .toList();
    }

    private boolean isEnumLike(JpDataType type) {
        if (type instanceof EnumRefType) {
            return true;
        }

        if (type instanceof ArrayType arrayType) {
            return isEnumLike(arrayType.element());
        }

        return false;
    }

    private String toPublicEnumReturnExpression(JpDataType type, StringBuilder implCall) {
        if (type instanceof EnumRefType) {
            return implCall + ".getDisplay()";
        }

        if (type instanceof ArrayType arrayType && arrayType.element() instanceof EnumRefType ref) {
            var enumType = TypeMapper.capitalize(ref.enumName());
            return implCall + ".map(" + enumType + "::getDisplay).toArray(String[]::new)";
        }

        throw new IllegalArgumentException("Unsupported enum bridge type: " + type);
    }

    private String mapType(JpDataType type) {
        boolean useRootJoinPointAlias = !config.hasBaseSpec();

        Function<String, String> jpMapper = name -> {
            if (useRootJoinPointAlias && name.equals(model.getGlobal().getName())) {
                return "Jp";
            }

            if (name.equals("joinpoint") || name.equals(model.getGlobal().getName())) {
                return TypeMapper.abstractClassName(model.getGlobal().getName())
                        + (config.hasBaseSpec() ? "<?>" : "<?, ?>");
            }
            return TypeMapper.abstractClassName(name) + "<?>";
        };

        return TypeMapper.toJavaType(
                type,
                "Self",
                jpMapper,
                TypeMapper::capitalize,
                TypeMapper::capitalize);
    }

    private String mapArrayCastType(ArrayType type) {
        boolean useRootJoinPointAlias = !config.hasBaseSpec();

        Function<String, String> jpMapper = name -> {
            if (useRootJoinPointAlias && name.equals(model.getGlobal().getName())) {
                return "Jp";
            }

            if (name.equals("joinpoint") || name.equals(model.getGlobal().getName())) {
                return TypeMapper.abstractClassName(model.getGlobal().getName());
            }
            return TypeMapper.abstractClassName(name);
        };

        return TypeMapper.toJavaType(
                type.element(),
                "Self",
                jpMapper,
                TypeMapper::capitalize,
                TypeMapper::capitalize);
    }

    private String getConstructorWeaverType(JpClass jpClass) {
        return jpClass.getParent().map(parent -> parent.equals(model.getGlobal()))
                .map(isRootChild -> isRootChild ? config.weaverClassName() : config.weaverName())
                .orElse(config.weaverName());
    }

    private String getConstructorWeaverImport(JpClass jpClass) {
        if (jpClass == model.getGlobal()) {
            return config.abstractWeaverPackage() + "." + config.weaverClassName();
        }

        return jpClass.getParent().map(parent -> parent.equals(model.getGlobal()))
                .map(isRootChild -> isRootChild
                        ? config.abstractWeaverPackage() + "." + config.weaverClassName()
                        : config.basePackage() + "." + config.weaverName())
                .orElse(config.basePackage() + "." + config.weaverName());
    }

    private boolean shouldGenerateWrapper(String name, List<Parameter> params) {
        var signature = TypeMapper.memberSignature(name, params);

        if (config.baseMemberSignatures().contains(signature)) {
            return false;
        }

        var parent = jpClass.getParent().orElse(null);
        while (parent != null) {
            if (hasMatchingSignature(parent.getOwnAttributes(), signature)
                    || hasMatchingSignature(parent.getOwnActions(), signature)) {
                return false;
            }

            parent = parent.getParent().orElse(null);
        }

        return true;
    }

    private boolean hasMatchingSignature(List<?> members, String signature) {
        for (var member : members) {
            if (member instanceof Attribute attr) {
                if (TypeMapper.memberSignature(attr.name(), attr.parameters()).equals(signature)) {
                    return true;
                }
                continue;
            }

            if (member instanceof Action action
                    && TypeMapper.memberSignature(action.name(), action.parameters()).equals(signature)) {
                return true;
            }
        }

        return false;
    }
}
