//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in
// JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.02.23 at 07:02:24 PM GMT
//

package org.lara.language.specification.artifactsmodel.schema;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ArtifactsList complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ArtifactsList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="global" type="{}Global" minOccurs="0"/>
 *         &lt;element name="artifact" type="{}Artifact" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="object" type="{}NewObject" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArtifactsList", propOrder = { "global", "artifact", "object" })
public class ArtifactsList {

	protected Global global;
	protected List<Artifact> artifact;
	protected List<NewObject> object;

	/**
	 * Gets the value of the global property.
	 * 
	 * @return possible object is {@link Global }
	 * 
	 */
	public Global getGlobal() {
		return global;
	}

	/**
	 * Sets the value of the global property.
	 * 
	 * @param value
	 *            allowed object is {@link Global }
	 * 
	 */
	public void setGlobal(Global value) {
		global = value;
	}

	/**
	 * Gets the value of the artifact property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the artifact property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getArtifact().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Artifact
	 * }
	 * 
	 * 
	 */
	public List<Artifact> getArtifact() {
		if (artifact == null) {
			artifact = new ArrayList<>();
		}
		return artifact;
	}

	/**
	 * Gets the value of the object property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the object property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getObject().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link NewObject
	 * }
	 * 
	 * 
	 */
	public List<NewObject> getObject() {
		if (object == null) {
			object = new ArrayList<>();
		}
		return object;
	}

}
