//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.28 at 01:37:33 AM CEST 
//


package org.lara.language.specification.artifactsmodel.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.lara.language.specification.artifactsmodel.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Artifacts_QNAME = new QName("", "artifacts");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.lara.language.specification.artifactsmodel.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ArtifactsList }
     * 
     */
    public ArtifactsList createArtifactsList() {
        return new ArtifactsList();
    }

    /**
     * Create an instance of {@link DefArgType }
     * 
     */
    public DefArgType createDefArgType() {
        return new DefArgType();
    }

    /**
     * Create an instance of {@link EnumDef }
     * 
     */
    public EnumDef createEnumDef() {
        return new EnumDef();
    }

    /**
     * Create an instance of {@link TypeDef }
     * 
     */
    public TypeDef createTypeDef() {
        return new TypeDef();
    }

    /**
     * Create an instance of {@link Attribute }
     * 
     */
    public Attribute createAttribute() {
        return new Attribute();
    }

    /**
     * Create an instance of {@link EnumValue }
     * 
     */
    public EnumValue createEnumValue() {
        return new EnumValue();
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link Artifact }
     * 
     */
    public Artifact createArtifact() {
        return new Artifact();
    }

    /**
     * Create an instance of {@link Global }
     * 
     */
    public Global createGlobal() {
        return new Global();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArtifactsList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "artifacts")
    public JAXBElement<ArtifactsList> createArtifacts(ArtifactsList value) {
        return new JAXBElement<ArtifactsList>(_Artifacts_QNAME, ArtifactsList.class, null, value);
    }

}
