//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in
// JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.02.23 at 07:02:24 PM GMT
//

package org.lara.language.specification.artifactsmodel.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the
 * org.language.specification.artifactsmodel.schema package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _Artifacts_QNAME = new QName("", "artifacts");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package:
	 * org.language.specification.artifactsmodel.schema
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link Attribute }
	 * 
	 */
	public Attribute createAttribute() {
		return new Attribute();
	}

	/**
	 * Create an instance of {@link Artifact }
	 * 
	 */
	public Artifact createArtifact() {
		return new Artifact();
	}

	/**
	 * Create an instance of {@link Parameter }
	 * 
	 */
	public Parameter createParameter() {
		return new Parameter();
	}

	/**
	 * Create an instance of {@link Global }
	 * 
	 */
	public Global createGlobal() {
		return new Global();
	}

	/**
	 * Create an instance of {@link NewObject }
	 * 
	 */
	public NewObject createNewObject() {
		return new NewObject();
	}

	/**
	 * Create an instance of {@link ArtifactsList }
	 * 
	 */
	public ArtifactsList createArtifactsList() {
		return new ArtifactsList();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ArtifactsList }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "artifacts")
	public JAXBElement<ArtifactsList> createArtifacts(ArtifactsList value) {
		return new JAXBElement<>(ObjectFactory._Artifacts_QNAME, ArtifactsList.class, null, value);
	}

}
