#!/usr/bin/env node

import fs from "fs";
import yargs from "yargs";
import { hideBin } from "yargs/helpers";
import { convertSpecification, type ConvertedEnum, type ConvertedJoinpoint } from "./convert-joinpoint-specification.ts";

import { generateJoinpoints, generateEnums } from "./generate-ts-joinpoints.ts";

async function buildInterfaces(
  inputFileName: string,
  laraJoinPointSpecificationImportPath: string,
  outputFileName: string
) {
  console.log("Hello from build-interfaces.ts");
  console.log("inputFile:", inputFileName);
  console.log(
    "LaraJoinPointSpecificationFile: ",
    laraJoinPointSpecificationImportPath
  );
  console.log("outputFile:", outputFileName);

  const { default: laraJsonSpecification } = await import(
    laraJoinPointSpecificationImportPath,
    {
      with: {
        type: "json",
      },
    }
  );
  const jsonSpecification = fs.readFileSync(inputFileName, "utf8");

  const laraSpecification = convertSpecification(
    laraJsonSpecification,
    undefined
  );
  const specification = convertSpecification(
    JSON.parse(jsonSpecification),
    laraSpecification
  );
  const importedEnums = specification.importEnums ?? [];

  // Create output file if it doesn't exist
  const outputFile = fs.openSync(outputFileName, "w");
  fs.writeSync(
    outputFile,
    `///////////////////////////////////////////////////
// This file is generated by build-interfaces.ts //
///////////////////////////////////////////////////

import {
  LaraJoinPoint,
  registerJoinpointMapper,
  wrapJoinPoint,
  unwrapJoinPoint,
${importedEnums.map((name) => `  ${name},`).join("\n")}
} from "@specs-feup/lara/api/LaraJoinPoint.ts";\n\n`
  );

  generateDefaultAttributeMappers(specification.joinpoints, outputFile);

  generateJoinpoints(specification.joinpoints, outputFile);
  generateEnums(
    specification.enums.filter((enumDef) => !importedEnums.includes(enumDef.name)),
    outputFile
  );

  generateJoinpointMappers(
    specification.joinpoints,
    specification.enums,
    outputFile
  );

  fs.closeSync(outputFile);
}

function generateJoinpointMappers(joinpoints: ConvertedJoinpoint[], enums: ConvertedEnum[], outputFile: number) {
  fs.writeSync(outputFile, `const JoinpointMapper = {\n`);
  for (const jp of joinpoints) {
    fs.writeSync(outputFile, `  ${jp.originalName}: ${jp.name},\n`);
  }
  fs.writeSync(outputFile, `};\n`);

  fs.writeSync(
    outputFile,
    `\nlet registered = false;
if (!registered) {
  registerJoinpointMapper(JoinpointMapper);
  registered = true;
}\n\n`
  );
}

function generateDefaultAttributeMappers(joinpoints: ConvertedJoinpoint[], outputFile: number) {
  fs.writeSync(outputFile, `type PrivateMapper = {\n`);
  for (const jp of joinpoints) {
    fs.writeSync(outputFile, `  "${jp.name}": typeof ${jp.name},\n`);
  }
  fs.writeSync(outputFile, `};\n\n`);

  fs.writeSync(outputFile, `type DefaultAttributeMap = {\n`);
  for (const jp of joinpoints) {
    if (jp.defaultAttribute) {
      fs.writeSync(outputFile, `  ${jp.name}: "${jp.defaultAttribute}",\n`);
    }
  }
  fs.writeSync(outputFile, `}\n\n`);
}

const args = yargs(hideBin(process.argv))
  .scriptName("lara-build-interfaces")
  .option("i", {
    alias: "input",
    describe: "Path to JSON config file",
    type: "string",
    demandOption: true,
  })
  .option("l", {
    alias: "lara",
    describe: "Path to JSON config file that describes LaraJoinPoint",
    type: "string",
    demandOption: true,
  })
  .option("o", {
    alias: "output",
    describe: "Path to the output file",
    type: "string",
    demandOption: true,
  })
  .help()
  .showHelpOnFail(true)
  .strict()
  .parseSync();

await buildInterfaces(args.i, args.l, args.o);
