package org.lara.weavergen2.emit;

import org.lara.langspec2.model.JpClass;
import org.lara.langspec2.model.WeaverModel;
import org.lara.weavergen2.java.JavaSourceBuilder;
import org.lara.weavergen2.java.TypeMapper;
import org.lara.weavergen2.model.GenerationProfile;

public final class JoinPointClassDeclarationEmitter {

    private final JpClass jpClass;
    private final WeaverModel model;
    private final GenerationProfile profile;
    private final JoinPointHierarchy hierarchy;

    public JoinPointClassDeclarationEmitter(JpClass jpClass, WeaverModel model, GenerationProfile profile,
            JoinPointHierarchy hierarchy) {
        this.jpClass = jpClass;
        this.model = model;
        this.profile = profile;
        this.hierarchy = hierarchy;
    }

    public String className() {
        return TypeMapper.abstractClassName(jpClass.getName());
    }

    public void open(JavaSourceBuilder sb) {
        sb.line("/**");
        sb.line(" * Auto-generated abstract class for the {@code " + jpClass.getName() + "} join point.");
        sb.line(" * <p>");
        sb.line(" * This class is generated by WeaverGen2 and should not be edited manually.");
        sb.line(" */");

        var superClass = superClass();
        if (superClass == null) {
            sb.openBlock("public abstract class " + className() + "<Self extends " + className()
                    + "<Self, Jp>, Jp extends " + className() + "<?, Jp>>");
        } else {
            sb.openBlock("public abstract class " + className() + "<Self extends " + className()
                    + "<Self>> extends " + superClass);
        }
        sb.line();
    }

    private String superClass() {
        if (!profile.hasBaseSpec()) {
            return null;
        }

        if (jpClass == model.getGlobal()) {
            return hierarchy.concreteSuperclass() + "<Self, " + className() + "<?>>";
        }

        return hierarchy.concreteSuperclass() + "<Self>";
    }
}
