# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI - Staging

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

jobs:
  build:

    runs-on: ubuntu-latest

    #defaults:
    #  run:
    #    working-directory: ./..

    steps:
    
    - uses: actions/checkout@v3
    
    #- name: Show working dir
    #  run: |
    #    ls -la
    #    
    #- name: Show parent dir
    #  run: |
    #    ls -la ../        
    #
    #- name: Show home dir
    #  run: |
    #    ls -la ~/
    
    - name: Cache ivy dependencies
      id: cache-nivy
      uses: actions/cache@v3
      env:
          cache-name: cache-ivy-dependencies
      with:
          # ivy dependencies cache files are stored in `~/.ivy2` on Linux/macOS
          path: ~/.ivy2
          key: ${{ runner.os }}-build-${{ env.cache-name }}    
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Generate build.xml
      run: | 
        wget -N http://specs.fe.up.pt/tools/eclipse-build.jar
        java -jar eclipse-build.jar https://github.com/specs-feup/specs-java-libs ./
        wget -N -O /usr/share/ant/lib/ivy-2.5.0.jar specs.fe.up.pt/libs/ivy-2.5.0.jar
    - name: Build with Ant
      run: |
        ant -noinput -buildfile build.xml
    #- name: Copy test results        
    #  run: |
    #    # Tried relative paths (not supported by junit action) and symlinks (are not followed by glob)
    #    # Resorted to copying the tests to a folder in the repo folder
    #    cp -a reports-eclipse-build/. lara-framework/junit-reports/        
    - name: Publish Test Report 
      uses: mikepenz/action-junit-report@v3.0.1
      if: always() # always run even if the previous step fails
      with:
        report_paths: '**/reports-eclipse-build/TEST-*.xml'
        summary: true
        #exclude_sources: ''        
