# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI - Staging

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

  # Daily at midnight
  schedule:
    - cron: '0 0 * * *'
 
permissions:
  checks: write
 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      # Because of scheduled runs, by default run on default branch
      with:
        ref: staging
        path: workspace/lara-framework

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Check out specs-java-libs repo
      uses: actions/checkout@v4
      with:
        repository: specs-feup/specs-java-libs
        path: workspace/specs-java-libs

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    # Setting up gradle multi-project would be helpful
    - name: Build and Test LaraFramework
      working-directory: workspace/lara-framework/LaraFramework
      run: gradle build test

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v4
      if: always()
      with:
        report_paths: 'workspace/lara-framework/**/build/test-results/test/TEST-*.xml'
        summary: true
